export type Zukan = { id: string; name: string; sugata?: string; en: string; type1: string; type2: string };

export const zukanList: Zukan[] = [
  { id: "0001", name: "フシギダネ", en: "Bulbasaur", type1: "くさ", type2: "どく" },
  { id: "0002", name: "フシギソウ", en: "Ivysaur", type1: "くさ", type2: "どく" },
  { id: "0003", name: "フシギバナ", en: "Venusaur", type1: "くさ", type2: "どく" },
  { id: "0004", name: "ヒトカゲ", en: "Charmander", type1: "ほの", type2: "" },
  { id: "0005", name: "リザード", en: "Charmeleon", type1: "ほの", type2: "" },
  { id: "0006", name: "リザードン", en: "Charizard", type1: "ほの", type2: "ひこ" },
  { id: "0007", name: "ゼニガメ", en: "Squirtle", type1: "みず", type2: "" },
  { id: "0008", name: "カメール", en: "Wartortle", type1: "みず", type2: "" },
  { id: "0009", name: "カメックス", en: "Blastoise", type1: "みず", type2: "" },
  { id: "0010", name: "キャタピー", en: "Caterpie", type1: "むし", type2: "" },
  { id: "0011", name: "トランセル", en: "Metapod", type1: "むし", type2: "" },
  { id: "0012", name: "バタフリー", en: "Butterfree", type1: "むし", type2: "ひこ" },
  { id: "0013", name: "ビードル", en: "Weedle", type1: "むし", type2: "どく" },
  { id: "0014", name: "コクーン", en: "Kakuna", type1: "むし", type2: "どく" },
  { id: "0015", name: "スピアー", en: "Beedrill", type1: "むし", type2: "どく" },
  { id: "0016", name: "ポッポ", en: "Pidgey", type1: "のま", type2: "ひこ" },
  { id: "0017", name: "ピジョン", en: "Pidgeotto", type1: "のま", type2: "ひこ" },
  { id: "0018", name: "ピジョット", en: "Pidgeot", type1: "のま", type2: "ひこ" },
  { id: "0019", sugata: "00", name: "コラッタ", en: "Rattata", type1: "のま", type2: "" },
  { id: "0019", sugata: "01", name: "コラッタ(アローラ)", en: "Rattata", type1: "あく", type2: "のま" },
  { id: "0020", sugata: "00", name: "ラッタ", en: "Raticate", type1: "のま", type2: "" },
  { id: "0020", sugata: "01", name: "ラッタ(アローラ)", en: "Raticate", type1: "あく", type2: "のま" },
  { id: "0021", name: "オニスズメ", en: "Spearow", type1: "のま", type2: "ひこ" },
  { id: "0022", name: "オニドリル", en: "Fearow", type1: "のま", type2: "ひこ" },
  { id: "0023", name: "アーボ", en: "Ekans", type1: "どく", type2: "" },
  { id: "0024", name: "アーボック", en: "Arbok", type1: "どく", type2: "" },
  { id: "0025", sugata: "00", name: "ピカチュウ", en: "Pikachu", type1: "でん", type2: "" },
  { id: "0025", sugata: "01", name: "ピカチュウ(アローラ)", en: "Pikachu", type1: "でん", type2: "" },
  { id: "0026", sugata: "00", name: "ライチュウ", en: "Raichu", type1: "でん", type2: "" },
  { id: "0026", sugata: "01", name: "ライチュウ(アローラ)", en: "Raichu", type1: "でん", type2: "えす" },
  { id: "0027", sugata: "00", name: "サンド", en: "Sandshrew", type1: "じめ", type2: "" },
  { id: "0027", sugata: "01", name: "サンド(アローラ)", en: "Sandshrew", type1: "こお", type2: "はが" },
  { id: "0028", sugata: "00", name: "サンドパン", en: "Sandslash", type1: "じめ", type2: "" },
  { id: "0028", sugata: "01", name: "サンドパン(アローラ)", en: "Sandslash", type1: "こお", type2: "はが" },
  { id: "0029", name: "ニドラン♀", en: "Nidoran♀", type1: "どく", type2: "" },
  { id: "0030", name: "ニドリーナ", en: "Nidorina", type1: "どく", type2: "" },
  { id: "0031", name: "ニドクイン", en: "Nidoqueen", type1: "どく", type2: "じめ" },
  { id: "0032", name: "ニドラン♂", en: "Nidoran♂", type1: "どく", type2: "" },
  { id: "0033", name: "ニドリーノ", en: "Nidorino", type1: "どく", type2: "" },
  { id: "0034", name: "ニドキング", en: "Nidoking", type1: "どく", type2: "じめ" },
  { id: "0035", name: "ピッピ", en: "Clefairy", type1: "ふぇ", type2: "" },
  { id: "0036", name: "ピクシー", en: "Clefable", type1: "ふぇ", type2: "" },
  { id: "0037", sugata: "00", name: "ロコン", en: "Vulpix", type1: "ほの", type2: "" },
  { id: "0037", sugata: "01", name: "ロコン(アローラ)", en: "Vulpix", type1: "こお", type2: "" },
  { id: "0038", sugata: "00", name: "キュウコン", en: "Ninetales", type1: "ほの", type2: "" },
  { id: "0038", sugata: "01", name: "キュウコン(アローラ)", en: "Ninetales", type1: "こお", type2: "ふぇ" },
  { id: "0039", name: "プリン", en: "Jigglypuff", type1: "のま", type2: "ふぇ" },
  { id: "0040", name: "プクリン", en: "Wigglytuff", type1: "のま", type2: "ふぇ" },
  { id: "0041", name: "ズバット", en: "Zubat", type1: "どく", type2: "ひこ" },
  { id: "0042", name: "ゴルバット", en: "Golbat", type1: "どく", type2: "ひこ" },
  { id: "0043", name: "ナゾノクサ", en: "Oddish", type1: "くさ", type2: "どく" },
  { id: "0044", name: "クサイハナ", en: "Gloom", type1: "くさ", type2: "どく" },
  { id: "0045", name: "ラフレシア", en: "Vileplume", type1: "くさ", type2: "どく" },
  { id: "0046", name: "パラス", en: "Paras", type1: "むし", type2: "くさ" },
  { id: "0047", name: "パラセクト", en: "Parasect", type1: "むし", type2: "くさ" },
  { id: "0048", name: "コンパン", en: "Venonat", type1: "むし", type2: "どく" },
  { id: "0049", name: "モルフォン", en: "Venomoth", type1: "むし", type2: "どく" },
  { id: "0050", sugata: "00", name: "ディグダ", en: "Diglett", type1: "じめ", type2: "" },
  { id: "0050", sugata: "01", name: "ディグダ(アローラ)", en: "Diglett", type1: "じめ", type2: "はが" },
  { id: "0051", sugata: "00", name: "ダグトリオ", en: "Dugtrio", type1: "じめ", type2: "" },
  { id: "0051", sugata: "01", name: "ダグトリオ(アローラ)", en: "Dugtrio", type1: "じめ", type2: "はが" },
  { id: "0052", sugata: "00", name: "ニャース", en: "Meowth", type1: "のま", type2: "" },
  { id: "0052", sugata: "01", name: "ニャース(アローラ)", en: "Meowth", type1: "あく", type2: "" },
  { id: "0052", sugata: "02", name: "ニャース(ガラル)", en: "Meowth", type1: "はが", type2: "" },
  { id: "0053", sugata: "00", name: "ペルシアン", en: "Persian", type1: "のま", type2: "" },
  { id: "0053", sugata: "01", name: "ペルシアン(アローラ)", en: "Persian", type1: "あく", type2: "" },
  { id: "0054", name: "コダック", en: "Psyduck", type1: "みず", type2: "" },
  { id: "0055", name: "ゴルダック", en: "Golduck", type1: "みず", type2: "" },
  { id: "0056", name: "マンキー", en: "Mankey", type1: "かく", type2: "" },
  { id: "0057", name: "オコリザル", en: "Primeape", type1: "かく", type2: "" },
  { id: "0058", sugata: "00", name: "ガーディ", en: "Growlithe", type1: "ほの", type2: "" },
  { id: "0058", sugata: "01", name: "ガーディ(ヒスイ)", en: "Growlithe", type1: "ほの", type2: "いわ" },
  { id: "0059", sugata: "00", name: "ウインディ", en: "Arcanine", type1: "ほの", type2: "" },
  { id: "0059", sugata: "01", name: "ウインディ(ヒスイ)", en: "Arcanine", type1: "ほの", type2: "いわ" },
  { id: "0060", name: "ニョロモ", en: "Poliwag", type1: "みず", type2: "" },
  { id: "0061", name: "ニョロゾ", en: "Poliwhirl", type1: "みず", type2: "" },
  { id: "0062", name: "ニョロボン", en: "Poliwrath", type1: "みず", type2: "かく" },
  { id: "0063", name: "ケーシィ", en: "Abra", type1: "えす", type2: "" },
  { id: "0064", name: "ユンゲラー", en: "Kadabra", type1: "えす", type2: "" },
  { id: "0065", name: "フーディン", en: "Alakazam", type1: "えす", type2: "" },
  { id: "0066", name: "ワンリキー", en: "Machop", type1: "かく", type2: "" },
  { id: "0067", name: "ゴーリキー", en: "Machoke", type1: "かく", type2: "" },
  { id: "0068", name: "カイリキー", en: "Machamp", type1: "かく", type2: "" },
  { id: "0069", name: "マダツボミ", en: "Bellsprout", type1: "くさ", type2: "どく" },
  { id: "0070", name: "ウツドン", en: "Weepinbell", type1: "くさ", type2: "どく" },
  { id: "0071", name: "ウツボット", en: "Victreebel", type1: "くさ", type2: "どく" },
  { id: "0072", name: "メノクラゲ", en: "Tentacool", type1: "みず", type2: "どく" },
  { id: "0073", name: "ドククラゲ", en: "Tentacruel", type1: "みず", type2: "どく" },
  { id: "0074", sugata: "00", name: "イシツブテ", en: "Geodude", type1: "いわ", type2: "じめ" },
  { id: "0074", sugata: "01", name: "イシツブテ(アローラ)", en: "Geodude", type1: "いわ", type2: "でん" },
  { id: "0075", sugata: "00", name: "ゴローン", en: "Graveler", type1: "いわ", type2: "じめ" },
  { id: "0075", sugata: "01", name: "ゴローン(アローラ)", en: "Graveler", type1: "いわ", type2: "でん" },
  { id: "0076", sugata: "00", name: "ゴローニャ", en: "Golem", type1: "いわ", type2: "じめ" },
  { id: "0076", sugata: "01", name: "ゴローニャ(アローラ)", en: "Golem", type1: "いわ", type2: "でん" },
  { id: "0077", sugata: "00", name: "ポニータ", en: "Ponyta", type1: "ほの", type2: "" },
  { id: "0077", sugata: "01", name: "ポニータ(ガラル)", en: "Ponyta", type1: "えす", type2: "" },
  { id: "0078", sugata: "00", name: "ギャロップ", en: "Rapidash", type1: "ほの", type2: "" },
  { id: "0078", sugata: "01", name: "ギャロップ(ガラル)", en: "Rapidash", type1: "えす", type2: "ふぇ" },
  { id: "0079", sugata: "00", name: "ヤドン", en: "Slowpoke", type1: "みず", type2: "えす" },
  { id: "0079", sugata: "01", name: "ヤドン(ガラル)", en: "Slowpoke", type1: "えす", type2: "" },
  { id: "0080", sugata: "00", name: "ヤドラン", en: "Slowbro", type1: "みず", type2: "えす" },
  { id: "0080", sugata: "02", name: "ヤドラン(ガラル)", en: "Slowbro", type1: "どく", type2: "えす" },
  { id: "0081", name: "コイル", en: "Magnemite", type1: "でん", type2: "はが" },
  { id: "0082", name: "レアコイル", en: "Magneton", type1: "でん", type2: "はが" },
  { id: "0083", sugata: "00", name: "カモネギ", en: "Farfetch'd", type1: "のま", type2: "ひこ" },
  { id: "0083", sugata: "01", name: "カモネギ(ガラル)", en: "Farfetch'd", type1: "かく", type2: "ひこ" },
  { id: "0084", name: "ドードー", en: "Doduo", type1: "のま", type2: "ひこ" },
  { id: "0085", name: "ドードリオ", en: "Dodrio", type1: "のま", type2: "ひこ" },
  { id: "0086", name: "パウワウ", en: "Seel", type1: "みず", type2: "" },
  { id: "0087", name: "ジュゴン", en: "Dewgong", type1: "みず", type2: "こお" },
  { id: "0088", sugata: "00", name: "ベトベター", en: "Grimer", type1: "どく", type2: "" },
  { id: "0088", sugata: "01", name: "ベトベター", en: "Grimer", type1: "どく", type2: "あく" },
  { id: "0089", sugata: "00", name: "ベトベトン", en: "Muk", type1: "どく", type2: "" },
  { id: "0089", sugata: "01", name: "ベトベトン", en: "Muk", type1: "どく", type2: "あく" },
  { id: "0090", name: "シェルダー", en: "Shellder", type1: "みず", type2: "" },
  { id: "0091", name: "パルシェン", en: "Cloyster", type1: "みず", type2: "こお" },
  { id: "0092", name: "ゴース", en: "Gastly", type1: "ごす", type2: "どく" },
  { id: "0093", name: "ごす", en: "Haunter", type1: "ごす", type2: "どく" },
  { id: "0094", name: "ゲンガー", en: "Gengar", type1: "ごす", type2: "どく" },
  { id: "0095", name: "イワーク", en: "Onix", type1: "いわ", type2: "じめ" },
  { id: "0096", name: "スリープ", en: "Drowzee", type1: "えす", type2: "" },
  { id: "0097", name: "スリーパー", en: "Hypno", type1: "えす", type2: "" },
  { id: "0098", name: "クラブ", en: "Krabby", type1: "みず", type2: "" },
  { id: "0099", name: "キングラー", en: "Kingler", type1: "みず", type2: "" },
  { id: "0100", sugata: "00", name: "ビリリダマ", en: "Voltorb", type1: "でん", type2: "" },
  { id: "0100", sugata: "01", name: "ビリリダマ(ヒスイ)", en: "Voltorb", type1: "でん", type2: "くさ" },
  { id: "0101", sugata: "00", name: "マルマイン", en: "Electrode", type1: "でん", type2: "" },
  { id: "0101", sugata: "01", name: "マルマイン(ヒスイ)", en: "Electrode", type1: "でん", type2: "くさ" },
  { id: "0102", name: "タマタマ", en: "Exeggcute", type1: "くさ", type2: "えす" },
  { id: "0103", sugata: "00", name: "ナッシー", en: "Exeggutor", type1: "くさ", type2: "えす" },
  { id: "0103", sugata: "01", name: "ナッシー(アローラ)", en: "Exeggutor", type1: "くさ", type2: "どら" },
  { id: "0104", name: "カラカラ", en: "Cubone", type1: "じめ", type2: "" },
  { id: "0105", sugata: "00", name: "ガラガラ", en: "Marowak", type1: "じめ", type2: "" },
  { id: "0105", sugata: "01", name: "ガラガラ(アローラ)", en: "Marowak", type1: "ほの", type2: "ごす" },
  { id: "0106", name: "サワムラー", en: "Hitmonlee", type1: "かく", type2: "" },
  { id: "0107", name: "エビワラー", en: "Hitmonchan", type1: "かく", type2: "" },
  { id: "0108", name: "ベロリンガ", en: "Lickitung", type1: "のま", type2: "" },
  { id: "0109", name: "ドガース", en: "Koffing", type1: "どく", type2: "" },
  { id: "0110", sugata: "00", name: "マタドガス", en: "Weezing", type1: "どく", type2: "" },
  { id: "0110", sugata: "01", name: "マタドガス(ガラル)", en: "Weezing", type1: "どく", type2: "ふぇ" },
  { id: "0111", name: "サイホーン", en: "Rhyhorn", type1: "じめ", type2: "いわ" },
  { id: "0112", name: "サイドン", en: "Rhydon", type1: "じめ", type2: "いわ" },
  { id: "0113", name: "ラッキー", en: "Chansey", type1: "のま", type2: "" },
  { id: "0114", name: "モンジャラ", en: "Tangela", type1: "くさ", type2: "" },
  { id: "0115", name: "ガルーラ", en: "Kangaskhan", type1: "のま", type2: "" },
  { id: "0116", name: "タッツー", en: "Horsea", type1: "みず", type2: "" },
  { id: "0117", name: "シードラ", en: "Seadra", type1: "みず", type2: "" },
  { id: "0118", name: "トサキント", en: "Goldeen", type1: "みず", type2: "" },
  { id: "0119", name: "アズマオウ", en: "Seaking", type1: "みず", type2: "" },
  { id: "0120", name: "ヒトデマン", en: "Staryu", type1: "みず", type2: "" },
  { id: "0121", name: "スターミー", en: "Starmie", type1: "みず", type2: "えす" },
  { id: "0122", sugata: "00", name: "バリヤード", en: "Mr. Mime", type1: "えす", type2: "ふぇ" },
  { id: "0122", sugata: "01", name: "バリヤード(ガラル)", en: "Mr. Mime", type1: "こお", type2: "えす" },
  { id: "0123", name: "ストライク", en: "Scyther", type1: "むし", type2: "ひこ" },
  { id: "0124", name: "ルージュラ", en: "Jynx", type1: "こお", type2: "えす" },
  { id: "0125", name: "エレブー", en: "Electabuzz", type1: "でん", type2: "" },
  { id: "0126", name: "ブーバー", en: "Magmar", type1: "ほの", type2: "" },
  { id: "0127", name: "カイロス", en: "Pinsir", type1: "むし", type2: "" },
  { id: "0128", sugata: "00", name: "ケンタロス", en: "Tauros", type1: "のま", type2: "" },
  { id: "0128", sugata: "01", name: "ケンタロス(パルデア闘)", en: "Tauros", type1: "かく", type2: "" },
  { id: "0128", sugata: "02", name: "ケンタロス(パルデア炎)", en: "Tauros", type1: "かく", type2: "ほの" },
  { id: "0128", sugata: "03", name: "ケンタロス(パルデア炎)", en: "Tauros", type1: "かく", type2: "みず" },
  { id: "0129", name: "コイキング", en: "Magikarp", type1: "みず", type2: "" },
  { id: "0130", name: "ギャラドス", en: "Gyarados", type1: "みず", type2: "ひこ" },
  { id: "0131", name: "ラプラス", en: "Lapras", type1: "みず", type2: "こお" },
  { id: "0132", name: "メタモン", en: "Ditto", type1: "のま", type2: "" },
  { id: "0133", name: "イーブイ", en: "Eevee", type1: "のま", type2: "" },
  { id: "0134", name: "シャワーズ", en: "Vaporeon", type1: "みず", type2: "" },
  { id: "0135", name: "サンダース", en: "Jolteon", type1: "でん", type2: "" },
  { id: "0136", name: "ブースター", en: "Flareon", type1: "ほの", type2: "" },
  { id: "0137", name: "ポリゴン", en: "Porygon", type1: "のま", type2: "" },
  { id: "0138", name: "オムナイト", en: "Omanyte", type1: "いわ", type2: "みず" },
  { id: "0139", name: "オムスター", en: "Omastar", type1: "いわ", type2: "みず" },
  { id: "0140", name: "カブト", en: "Kabuto", type1: "いわ", type2: "みず" },
  { id: "0141", name: "カブトプス", en: "Kabutops", type1: "いわ", type2: "みず" },
  { id: "0142", name: "プテラ", en: "Aerodactyl", type1: "いわ", type2: "ひこ" },
  { id: "0143", name: "カビゴン", en: "Snorlax", type1: "のま", type2: "" },
  { id: "0144", sugata: "00", name: "フリーザー", en: "Articuno", type1: "こお", type2: "ひこ" },
  { id: "0144", sugata: "01", name: "フリーザー(ガラル)", en: "Articuno", type1: "えす", type2: "ひこ" },
  { id: "0145", sugata: "00", name: "サンダー", en: "Zapdos", type1: "でん", type2: "ひこ" },
  { id: "0145", sugata: "01", name: "サンダー(ガラル)", en: "Zapdos", type1: "かく", type2: "ひこ" },
  { id: "0146", sugata: "00", name: "ファイヤー", en: "Moltres", type1: "ほの", type2: "ひこ" },
  { id: "0146", sugata: "01", name: "ファイヤー(ガラル)", en: "Moltres", type1: "あく", type2: "ひこ" },
  { id: "0147", name: "ミニリュウ", en: "Dratini", type1: "どら", type2: "" },
  { id: "0148", name: "ハクリュー", en: "Dragonair", type1: "どら", type2: "" },
  { id: "0149", name: "カイリュー", en: "Dragonite", type1: "どら", type2: "ひこ" },
  { id: "0150", name: "ミュウツー", en: "Mewtwo", type1: "えす", type2: "" },
  { id: "0151", name: "ミュウ", en: "Mew", type1: "えす", type2: "" },
  { id: "0152", name: "チコリータ", en: "Chikorita", type1: "くさ", type2: "" },
  { id: "0153", name: "ベイリーフ", en: "Bayleef", type1: "くさ", type2: "" },
  { id: "0154", name: "メガニウム", en: "Meganium", type1: "くさ", type2: "" },
  { id: "0155", name: "ヒノアラシ", en: "Cyndaquil", type1: "ほの", type2: "" },
  { id: "0156", name: "マグマラシ", en: "Quilava", type1: "ほの", type2: "" },
  { id: "0157", sugata: "00", name: "バクフーン", en: "Typhlosion", type1: "ほの", type2: "" },
  { id: "0157", sugata: "01", name: "バクフーン(ヒスイ)", en: "Typhlosion", type1: "ほの", type2: "ごす" },
  { id: "0158", name: "ワニノコ", en: "Totodile", type1: "みず", type2: "" },
  { id: "0159", name: "アリゲイツ", en: "Croconaw", type1: "みず", type2: "" },
  { id: "0160", name: "オーダイル", en: "Feraligatr", type1: "みず", type2: "" },
  { id: "0161", name: "オタチ", en: "Sentret", type1: "のま", type2: "" },
  { id: "0162", name: "オオタチ", en: "Furret", type1: "のま", type2: "" },
  { id: "0163", name: "ホーホー", en: "Hoothoot", type1: "のま", type2: "ひこ" },
  { id: "0164", name: "ヨルノズク", en: "Noctowl", type1: "のま", type2: "ひこ" },
  { id: "0165", name: "レディバ", en: "Ledyba", type1: "むし", type2: "ひこ" },
  { id: "0166", name: "レディアン", en: "Ledian", type1: "むし", type2: "ひこ" },
  { id: "0167", name: "イトマル", en: "Spinarak", type1: "むし", type2: "どく" },
  { id: "0168", name: "アリアドス", en: "Ariados", type1: "むし", type2: "どく" },
  { id: "0169", name: "クロバット", en: "Crobat", type1: "どく", type2: "ひこ" },
  { id: "0170", name: "チョンチー", en: "Chinchou", type1: "みず", type2: "でん" },
  { id: "0171", name: "ランターン", en: "Lanturn", type1: "みず", type2: "でん" },
  { id: "0172", name: "ピチュー", en: "Pichu", type1: "でん", type2: "" },
  { id: "0173", name: "ピィ", en: "Cleffa", type1: "ふぇ", type2: "" },
  { id: "0174", name: "ププリン", en: "Igglybuff", type1: "のま", type2: "ふぇ" },
  { id: "0175", name: "トゲピー", en: "Togepi", type1: "ふぇ", type2: "" },
  { id: "0176", name: "トゲチック", en: "Togetic", type1: "ふぇ", type2: "ひこ" },
  { id: "0177", name: "ネイティ", en: "Natu", type1: "えす", type2: "ひこ" },
  { id: "0178", name: "ネイティオ", en: "Xatu", type1: "えす", type2: "ひこ" },
  { id: "0179", name: "メリープ", en: "Mareep", type1: "でん", type2: "" },
  { id: "0180", name: "モココ", en: "Flaaffy", type1: "でん", type2: "" },
  { id: "0181", name: "デンリュウ", en: "Ampharos", type1: "でん", type2: "" },
  { id: "0182", name: "キレイハナ", en: "Bellossom", type1: "くさ", type2: "" },
  { id: "0183", name: "マリル", en: "Marill", type1: "みず", type2: "ふぇ" },
  { id: "0184", name: "マリルリ", en: "Azumarill", type1: "みず", type2: "ふぇ" },
  { id: "0185", name: "ウソッキー", en: "Sudowoodo", type1: "いわ", type2: "" },
  { id: "0186", name: "ニョロトノ", en: "Politoed", type1: "みず", type2: "" },
  { id: "0187", name: "ハネッコ", en: "Hoppip", type1: "くさ", type2: "ひこ" },
  { id: "0188", name: "ポポッコ", en: "Skiploom", type1: "くさ", type2: "ひこ" },
  { id: "0189", name: "ワタッコ", en: "Jumpluff", type1: "くさ", type2: "ひこ" },
  { id: "0190", name: "エイパム", en: "Aipom", type1: "のま", type2: "" },
  { id: "0191", name: "ヒマナッツ", en: "Sunkern", type1: "くさ", type2: "" },
  { id: "0192", name: "キマワリ", en: "Sunflora", type1: "くさ", type2: "" },
  { id: "0193", name: "ヤンヤンマ", en: "Yanma", type1: "むし", type2: "ひこ" },
  { id: "0194", sugata: "00", name: "ウパー", en: "Wooper", type1: "みず", type2: "じめ" },
  { id: "0194", sugata: "01", name: "ウパー(パルデア)", en: "Wooper", type1: "どく", type2: "じめ" },
  { id: "0195", name: "ヌオー", en: "Quagsire", type1: "みず", type2: "じめ" },
  { id: "0196", name: "エーフィ", en: "Espeon", type1: "えす", type2: "" },
  { id: "0197", name: "ブラッキー", en: "Umbreon", type1: "あく", type2: "" },
  { id: "0198", name: "ヤミカラス", en: "Murkrow", type1: "あく", type2: "ひこ" },
  { id: "0199", sugata: "00", name: "ヤドキング", en: "Slowking", type1: "みず", type2: "えす" },
  { id: "0199", sugata: "01", name: "ヤドキング(ガラル)", en: "Slowking", type1: "どく", type2: "えす" },
  { id: "0200", name: "ムウマ", en: "Misdreavus", type1: "ごす", type2: "" },
  { id: "0201", name: "アンノーン", en: "Unown", type1: "えす", type2: "" },
  { id: "0202", name: "ソーナンス", en: "Wobbuffet", type1: "えす", type2: "" },
  { id: "0203", name: "キリンリキ", en: "Girafarig", type1: "のま", type2: "えす" },
  { id: "0204", name: "クヌギダマ", en: "Pineco", type1: "むし", type2: "" },
  { id: "0205", name: "フォレトス", en: "Forretress", type1: "むし", type2: "はが" },
  { id: "0206", name: "ノコッチ", en: "Dunsparce", type1: "のま", type2: "" },
  { id: "0207", name: "グライガー", en: "Gligar", type1: "じめ", type2: "ひこ" },
  { id: "0208", name: "ハガネール", en: "Steelix", type1: "はが", type2: "じめ" },
  { id: "0209", name: "ブルー", en: "Snubbull", type1: "ふぇ", type2: "" },
  { id: "0210", name: "グランブル", en: "Granbull", type1: "ふぇ", type2: "" },
  { id: "0211", sugata: "00", name: "ハリーセン", en: "Qwilfish", type1: "みず", type2: "どく" },
  { id: "0211", sugata: "01", name: "ハリーセン(ヒスイ)", en: "Qwilfish", type1: "あく", type2: "どく" },
  { id: "0212", name: "ハッサム", en: "Scizor", type1: "むし", type2: "はが" },
  { id: "0213", name: "ツボツボ", en: "Shuckle", type1: "むし", type2: "いわ" },
  { id: "0214", name: "ヘラクロス", en: "Heracross", type1: "むし", type2: "かく" },
  { id: "0215", sugata: "00", name: "ニューラ", en: "Sneasel", type1: "あく", type2: "こお" },
  { id: "0215", sugata: "01", name: "ニューラ(ヒスイ)", en: "Sneasel", type1: "かく", type2: "どく" },
  { id: "0216", name: "ヒメグマ", en: "Teddiursa", type1: "のま", type2: "" },
  { id: "0217", name: "リングマ", en: "Ursaring", type1: "のま", type2: "" },
  { id: "0218", name: "マグマッグ", en: "Slugma", type1: "ほの", type2: "" },
  { id: "0219", name: "マグカルゴ", en: "Magcargo", type1: "ほの", type2: "いわ" },
  { id: "0220", name: "ウリムー", en: "Swinub", type1: "こお", type2: "じめ" },
  { id: "0221", name: "イノムー", en: "Piloswine", type1: "こお", type2: "じめ" },
  { id: "0222", sugata: "00", name: "サニーゴ", en: "Corsola", type1: "みず", type2: "いわ" },
  { id: "0222", sugata: "01", name: "サニーゴ(ガラル)", en: "Corsola", type1: "ごす", type2: "" },
  { id: "0223", name: "テッポウオ", en: "Remoraid", type1: "みず", type2: "" },
  { id: "0224", name: "オクタン", en: "Octillery", type1: "みず", type2: "" },
  { id: "0225", name: "デリバード", en: "Delibird", type1: "こお", type2: "ひこ" },
  { id: "0226", name: "マンタイン", en: "Mantine", type1: "みず", type2: "ひこ" },
  { id: "0227", name: "エアームド", en: "Skarmory", type1: "はが", type2: "ひこ" },
  { id: "0228", name: "デルビル", en: "Houndour", type1: "あく", type2: "ほの" },
  { id: "0229", name: "ヘルガー", en: "Houndoom", type1: "あく", type2: "ほの" },
  { id: "0230", name: "キングドラ", en: "Kingdra", type1: "みず", type2: "どら" },
  { id: "0231", name: "ゴマゾウ", en: "Phanpy", type1: "じめ", type2: "" },
  { id: "0232", name: "ドンファン", en: "Donphan", type1: "じめ", type2: "" },
  { id: "0233", name: "ポリゴン２", en: "Porygon2", type1: "のま", type2: "" },
  { id: "0234", name: "オドシシ", en: "Stantler", type1: "のま", type2: "" },
  { id: "0235", name: "ドーブル", en: "Smeargle", type1: "のま", type2: "" },
  { id: "0236", name: "バルキー", en: "Tyrogue", type1: "かく", type2: "" },
  { id: "0237", name: "カポエラー", en: "Hitmontop", type1: "かく", type2: "" },
  { id: "0238", name: "ムチュール", en: "Smoochum", type1: "こお", type2: "えす" },
  { id: "0239", name: "エレキッド", en: "Elekid", type1: "でん", type2: "" },
  { id: "0240", name: "ブビィ", en: "Magby", type1: "ほの", type2: "" },
  { id: "0241", name: "ミルタンク", en: "Miltank", type1: "のま", type2: "" },
  { id: "0242", name: "ハピナス", en: "Blissey", type1: "のま", type2: "" },
  { id: "0243", name: "ライコウ", en: "Raikou", type1: "でん", type2: "" },
  { id: "0244", name: "エンテイ", en: "Entei", type1: "ほの", type2: "" },
  { id: "0245", name: "スイクン", en: "Suicune", type1: "みず", type2: "" },
  { id: "0246", name: "ヨーギラス", en: "Larvitar", type1: "いわ", type2: "じめ" },
  { id: "0247", name: "サナギラス", en: "Pupitar", type1: "いわ", type2: "じめ" },
  { id: "0248", name: "バンギラス", en: "Tyranitar", type1: "いわ", type2: "あく" },
  { id: "0249", name: "ルギア", en: "Lugia", type1: "えす", type2: "ひこ" },
  { id: "0250", name: "ホウオウ", en: "Ho-Oh", type1: "ほの", type2: "ひこ" },
  { id: "0251", name: "セレビィ", en: "Celebi", type1: "えす", type2: "くさ" },
  { id: "0252", name: "キモリ", en: "Treecko", type1: "くさ", type2: "" },
  { id: "0253", name: "ジュプトル", en: "Grovyle", type1: "くさ", type2: "" },
  { id: "0254", name: "ジュカイン", en: "Sceptile", type1: "くさ", type2: "" },
  { id: "0255", name: "アチャモ", en: "Torchic", type1: "ほの", type2: "" },
  { id: "0256", name: "ワカシャモ", en: "Combusken", type1: "ほの", type2: "かく" },
  { id: "0257", name: "バシャーモ", en: "Blaziken", type1: "ほの", type2: "かく" },
  { id: "0258", name: "ミズゴロウ", en: "Mudkip", type1: "みず", type2: "" },
  { id: "0259", name: "ヌマクロー", en: "Marshtomp", type1: "みず", type2: "じめ" },
  { id: "0260", name: "ラグラージ", en: "Swampert", type1: "みず", type2: "じめ" },
  { id: "0261", name: "ポチエナ", en: "Poochyena", type1: "あく", type2: "" },
  { id: "0262", name: "グラエナ", en: "Mightyena", type1: "あく", type2: "" },
  { id: "0263", sugata: "00", name: "ジグザグマ", en: "Zigzagoon", type1: "のま", type2: "" },
  { id: "0263", sugata: "01", name: "ジグザグマ(ガラル)", en: "Zigzagoon", type1: "あく", type2: "のま" },
  { id: "0264", sugata: "00", name: "マッスグマ", en: "Linoone", type1: "のま", type2: "" },
  { id: "0264", sugata: "01", name: "マッスグマ(ガラル)", en: "Linoone", type1: "あく", type2: "のま" },
  { id: "0265", name: "ケムッソ", en: "Wurmple", type1: "むし", type2: "" },
  { id: "0266", name: "カラサリス", en: "Silcoon", type1: "むし", type2: "" },
  { id: "0267", name: "アゲハント", en: "Beautifly", type1: "むし", type2: "ひこ" },
  { id: "0268", name: "マユルド", en: "Cascoon", type1: "むし", type2: "" },
  { id: "0269", name: "ドクケイル", en: "Dustox", type1: "むし", type2: "どく" },
  { id: "0270", name: "ハスボー", en: "Lotad", type1: "みず", type2: "くさ" },
  { id: "0271", name: "ハスブレロ", en: "Lombre", type1: "みず", type2: "くさ" },
  { id: "0272", name: "ルンパッパ", en: "Ludicolo", type1: "みず", type2: "くさ" },
  { id: "0273", name: "タネボー", en: "Seedot", type1: "くさ", type2: "" },
  { id: "0274", name: "コノハナ", en: "Nuzleaf", type1: "くさ", type2: "あく" },
  { id: "0275", name: "ダーテング", en: "Shiftry", type1: "くさ", type2: "あく" },
  { id: "0276", name: "スバメ", en: "Taillow", type1: "のま", type2: "ひこ" },
  { id: "0277", name: "オオスバメ", en: "Swellow", type1: "のま", type2: "ひこ" },
  { id: "0278", name: "キャモメ", en: "Wingull", type1: "みず", type2: "ひこ" },
  { id: "0279", name: "ペリッパー", en: "Pelipper", type1: "みず", type2: "ひこ" },
  { id: "0280", name: "ラルトス", en: "Ralts", type1: "えす", type2: "ふぇ" },
  { id: "0281", name: "キルリア", en: "Kirlia", type1: "えす", type2: "ふぇ" },
  { id: "0282", name: "サーナイト", en: "Gardevoir", type1: "えす", type2: "ふぇ" },
  { id: "0283", name: "アメタマ", en: "Surskit", type1: "むし", type2: "みず" },
  { id: "0284", name: "アメモース", en: "Masquerain", type1: "むし", type2: "ひこ" },
  { id: "0285", name: "キノココ", en: "Shroomish", type1: "くさ", type2: "" },
  { id: "0286", name: "キノガッサ", en: "Breloom", type1: "くさ", type2: "かく" },
  { id: "0287", name: "ナマケロ", en: "Slakoth", type1: "のま", type2: "" },
  { id: "0288", name: "ヤルキモノ", en: "Vigoroth", type1: "のま", type2: "" },
  { id: "0289", name: "ケッキング", en: "Slaking", type1: "のま", type2: "" },
  { id: "0290", name: "ツチニン", en: "Nincada", type1: "むし", type2: "じめ" },
  { id: "0291", name: "テッカニン", en: "Ninjask", type1: "むし", type2: "ひこ" },
  { id: "0292", name: "ヌケニン", en: "Shedinja", type1: "むし", type2: "ごす" },
  { id: "0293", name: "ゴニョニョ", en: "Whismur", type1: "のま", type2: "" },
  { id: "0294", name: "ドゴーム", en: "Loudred", type1: "のま", type2: "" },
  { id: "0295", name: "バクオング", en: "Exploud", type1: "のま", type2: "" },
  { id: "0296", name: "マクノシタ", en: "Makuhita", type1: "かく", type2: "" },
  { id: "0297", name: "ハリテヤマ", en: "Hariyama", type1: "かく", type2: "" },
  { id: "0298", name: "ルリリ", en: "Azurill", type1: "のま", type2: "ふぇ" },
  { id: "0299", name: "ノズパス", en: "Nosepass", type1: "いわ", type2: "" },
  { id: "0300", name: "エネコ", en: "Skitty", type1: "のま", type2: "" },
  { id: "0301", name: "エネコロロ", en: "Delcatty", type1: "のま", type2: "" },
  { id: "0302", name: "ヤミラミ", en: "Sableye", type1: "あく", type2: "ごす" },
  { id: "0303", name: "クチート", en: "Mawile", type1: "はが", type2: "ふぇ" },
  { id: "0304", name: "ココドラ", en: "Aron", type1: "はが", type2: "いわ" },
  { id: "0305", name: "コドラ", en: "Lairon", type1: "はが", type2: "いわ" },
  { id: "0306", name: "ボスゴドラ", en: "Aggron", type1: "はが", type2: "いわ" },
  { id: "0307", name: "アサナン", en: "Meditite", type1: "かく", type2: "えす" },
  { id: "0308", name: "チャーレム", en: "Medicham", type1: "かく", type2: "えす" },
  { id: "0309", name: "ラクライ", en: "Electrike", type1: "でん", type2: "" },
  { id: "0310", name: "ライボルト", en: "Manectric", type1: "でん", type2: "" },
  { id: "0311", name: "プラスル", en: "Plusle", type1: "でん", type2: "" },
  { id: "0312", name: "マイナン", en: "Minun", type1: "でん", type2: "" },
  { id: "0313", name: "バルビート", en: "Volbeat", type1: "むし", type2: "" },
  { id: "0314", name: "イルミーゼ", en: "Illumise", type1: "むし", type2: "" },
  { id: "0315", name: "ロゼリア", en: "Roselia", type1: "くさ", type2: "どく" },
  { id: "0316", name: "ゴクリン", en: "Gulpin", type1: "どく", type2: "" },
  { id: "0317", name: "マルノーム", en: "Swalot", type1: "どく", type2: "" },
  { id: "0318", name: "キバニア", en: "Carvanha", type1: "みず", type2: "あく" },
  { id: "0319", name: "サメハダー", en: "Sharpedo", type1: "みず", type2: "あく" },
  { id: "0320", name: "ホエルコ", en: "Wailmer", type1: "みず", type2: "" },
  { id: "0321", name: "ホエルオー", en: "Wailord", type1: "みず", type2: "" },
  { id: "0322", name: "ドンメル", en: "Numel", type1: "ほの", type2: "じめ" },
  { id: "0323", name: "バクーダ", en: "Camerupt", type1: "ほの", type2: "じめ" },
  { id: "0324", name: "コータス", en: "Torkoal", type1: "ほの", type2: "" },
  { id: "0325", name: "バネブー", en: "Spoink", type1: "えす", type2: "" },
  { id: "0326", name: "ブーピッグ", en: "Grumpig", type1: "えす", type2: "" },
  { id: "0327", name: "パッチール", en: "Spinda", type1: "のま", type2: "" },
  { id: "0328", name: "ナックラー", en: "Trapinch", type1: "じめ", type2: "" },
  { id: "0329", name: "ビブラーバ", en: "Vibrava", type1: "じめ", type2: "どら" },
  { id: "0330", name: "フライゴン", en: "Flygon", type1: "じめ", type2: "どら" },
  { id: "0331", name: "サボネア", en: "Cacnea", type1: "くさ", type2: "" },
  { id: "0332", name: "ノクタス", en: "Cacturne", type1: "くさ", type2: "あく" },
  { id: "0333", name: "チルット", en: "Swablu", type1: "のま", type2: "ひこ" },
  { id: "0334", name: "チルタリス", en: "Altaria", type1: "どら", type2: "ひこ" },
  { id: "0335", name: "ザングース", en: "Zangoose", type1: "のま", type2: "" },
  { id: "0336", name: "ハブネーク", en: "Seviper", type1: "どく", type2: "" },
  { id: "0337", name: "ルナトーン", en: "Lunatone", type1: "いわ", type2: "えす" },
  { id: "0338", name: "ソルロック", en: "Solrock", type1: "いわ", type2: "えす" },
  { id: "0339", name: "ドジョッチ", en: "Barboach", type1: "みず", type2: "じめ" },
  { id: "0340", name: "ナマズン", en: "Whiscash", type1: "みず", type2: "じめ" },
  { id: "0341", name: "ヘイガニ", en: "Corphish", type1: "みず", type2: "" },
  { id: "0342", name: "シザリガー", en: "Crawdaunt", type1: "みず", type2: "あく" },
  { id: "0343", name: "ヤジロン", en: "Baltoy", type1: "じめ", type2: "えす" },
  { id: "0344", name: "ネンドール", en: "Claydol", type1: "じめ", type2: "えす" },
  { id: "0345", name: "リリーラ", en: "Lileep", type1: "いわ", type2: "くさ" },
  { id: "0346", name: "ユレイドル", en: "Cradily", type1: "いわ", type2: "くさ" },
  { id: "0347", name: "アノプス", en: "Anorith", type1: "いわ", type2: "むし" },
  { id: "0348", name: "アーマルド", en: "Armaldo", type1: "いわ", type2: "むし" },
  { id: "0349", name: "ヒンバス", en: "Feebas", type1: "みず", type2: "" },
  { id: "0350", name: "ミロカロス", en: "Milotic", type1: "みず", type2: "" },
  { id: "0351", name: "ポワルン", en: "Castform", type1: "のま", type2: "" },
  { id: "0352", name: "カクレオン", en: "Kecleon", type1: "のま", type2: "" },
  { id: "0353", name: "カゲボウズ", en: "Shuppet", type1: "ごす", type2: "" },
  { id: "0354", name: "ジュペッタ", en: "Banette", type1: "ごす", type2: "" },
  { id: "0355", name: "ヨマワル", en: "Duskull", type1: "ごす", type2: "" },
  { id: "0356", name: "サマヨール", en: "Dusclops", type1: "ごす", type2: "" },
  { id: "0357", name: "トロピウス", en: "Tropius", type1: "くさ", type2: "ひこ" },
  { id: "0358", name: "チリーン", en: "Chimecho", type1: "えす", type2: "" },
  { id: "0359", name: "アブソル", en: "Absol", type1: "あく", type2: "" },
  { id: "0360", name: "ソーナノ", en: "Wynaut", type1: "えす", type2: "" },
  { id: "0361", name: "ユキワラシ", en: "Snorunt", type1: "こお", type2: "" },
  { id: "0362", name: "オニゴーリ", en: "Glalie", type1: "こお", type2: "" },
  { id: "0363", name: "タマザラシ", en: "Spheal", type1: "こお", type2: "みず" },
  { id: "0364", name: "トドグラー", en: "Sealeo", type1: "こお", type2: "みず" },
  { id: "0365", name: "トドゼルガ", en: "Walrein", type1: "こお", type2: "みず" },
  { id: "0366", name: "パールル", en: "Clamperl", type1: "みず", type2: "" },
  { id: "0367", name: "ハンテール", en: "Huntail", type1: "みず", type2: "" },
  { id: "0368", name: "サクラビス", en: "Gorebyss", type1: "みず", type2: "" },
  { id: "0369", name: "ジーランス", en: "Relicanth", type1: "みず", type2: "いわ" },
  { id: "0370", name: "ラブカス", en: "Luvdisc", type1: "みず", type2: "" },
  { id: "0371", name: "タツベイ", en: "Bagon", type1: "どら", type2: "" },
  { id: "0372", name: "コモルー", en: "Shelgon", type1: "どら", type2: "" },
  { id: "0373", name: "ボーマンダ", en: "Salamence", type1: "どら", type2: "ひこ" },
  { id: "0374", name: "ダンバル", en: "Beldum", type1: "はが", type2: "えす" },
  { id: "0375", name: "メタング", en: "Metang", type1: "はが", type2: "えす" },
  { id: "0376", name: "メタグロス", en: "Metagross", type1: "はが", type2: "えす" },
  { id: "0377", name: "レジロック", en: "Regirock", type1: "いわ", type2: "" },
  { id: "0378", name: "レジアイス", en: "Regice", type1: "こお", type2: "" },
  { id: "0379", name: "レジスチル", en: "Registeel", type1: "はが", type2: "" },
  { id: "0380", name: "ラティアス", en: "Latias", type1: "どら", type2: "えす" },
  { id: "0381", name: "ラティオス", en: "Latios", type1: "どら", type2: "えす" },
  { id: "0382", name: "カイオーガ", en: "Kyogre", type1: "みず", type2: "" },
  { id: "0383", name: "グラードン", en: "Groudon", type1: "じめ", type2: "" },
  { id: "0384", name: "レックウザ", en: "Rayquaza", type1: "どら", type2: "ひこ" },
  { id: "0385", name: "ジラーチ", en: "Jirachi", type1: "はが", type2: "えす" },
  { id: "0386", sugata: "00", name: "デオキシス(ノーマル)", en: "Deoxys", type1: "えす", type2: "" },
  { id: "0386", sugata: "01", name: "デオキシス(アタック)", en: "Deoxys", type1: "えす", type2: "" },
  { id: "0386", sugata: "02", name: "デオキシス(ディフェンス)", en: "Deoxys", type1: "えす", type2: "" },
  { id: "0386", sugata: "03", name: "デオキシス(スピード)", en: "Deoxys", type1: "えす", type2: "" },
  { id: "0387", name: "ナエトル", en: "Turtwig", type1: "くさ", type2: "" },
  { id: "0388", name: "ハヤシガメ", en: "Grotle", type1: "くさ", type2: "" },
  { id: "0389", name: "ドダイトス", en: "Torterra", type1: "くさ", type2: "じめ" },
  { id: "0390", name: "ヒコザル", en: "Chimchar", type1: "ほの", type2: "" },
  { id: "0391", name: "モウカザル", en: "Monferno", type1: "ほの", type2: "かく" },
  { id: "0392", name: "ゴウカザル", en: "Infernape", type1: "ほの", type2: "かく" },
  { id: "0393", name: "ポッチャマ", en: "Piplup", type1: "みず", type2: "" },
  { id: "0394", name: "ポッタイシ", en: "Prinplup", type1: "みず", type2: "" },
  { id: "0395", name: "エンペルト", en: "Empoleon", type1: "みず", type2: "はが" },
  { id: "0396", name: "ムックル", en: "Starly", type1: "のま", type2: "ひこ" },
  { id: "0397", name: "ムクバード", en: "Staravia", type1: "のま", type2: "ひこ" },
  { id: "0398", name: "ムクホーク", en: "Staraptor", type1: "のま", type2: "ひこ" },
  { id: "0399", name: "ビッパ", en: "Bidoof", type1: "のま", type2: "" },
  { id: "0400", name: "ビーダル", en: "Bibarel", type1: "のま", type2: "みず" },
  { id: "0401", name: "コロボーシ", en: "Kricketot", type1: "むし", type2: "" },
  { id: "0402", name: "コロトック", en: "Kricketune", type1: "むし", type2: "" },
  { id: "0403", name: "コリンク", en: "Shinx", type1: "でん", type2: "" },
  { id: "0404", name: "ルクシオ", en: "Luxio", type1: "でん", type2: "" },
  { id: "0405", name: "レントラー", en: "Luxray", type1: "でん", type2: "" },
  { id: "0406", name: "スボミー", en: "Budew", type1: "くさ", type2: "どく" },
  { id: "0407", name: "ロズレイド", en: "Roserade", type1: "くさ", type2: "どく" },
  { id: "0408", name: "ズガイドス", en: "Cranidos", type1: "いわ", type2: "" },
  { id: "0409", name: "ラムパルド", en: "Rampardos", type1: "いわ", type2: "" },
  { id: "0410", name: "タテトプス", en: "Shieldon", type1: "いわ", type2: "はが" },
  { id: "0411", name: "トリデプス", en: "Bastiodon", type1: "いわ", type2: "はが" },
  { id: "0412", sugata: "00", name: "ミノムッチ(くさち)", en: "Burmy", type1: "むし", type2: "" },
  { id: "0412", sugata: "01", name: "ミノムッチ(すなち)", en: "Burmy", type1: "むし", type2: "" },
  { id: "0412", sugata: "02", name: "ミノムッチ(ゴミ)", en: "Burmy", type1: "むし", type2: "" },
  { id: "0413", sugata: "00", name: "ミノマダム(くさち)", en: "Wormadam", type1: "むし", type2: "くさ" },
  { id: "0413", sugata: "01", name: "ミノマダム(すなち)", en: "Wormadam", type1: "むし", type2: "じめ" },
  { id: "0413", sugata: "02", name: "ミノマダム(ゴミ)", en: "Wormadam", type1: "むし", type2: "はが" },
  { id: "0414", name: "ガーメイル", en: "Mothim", type1: "むし", type2: "ひこ" },
  { id: "0415", name: "ミツハニー", en: "Combee", type1: "むし", type2: "ひこ" },
  { id: "0416", name: "ビークイン", en: "Vespiquen", type1: "むし", type2: "ひこ" },
  { id: "0417", name: "パチリス", en: "Pachirisu", type1: "でん", type2: "" },
  { id: "0418", name: "ブイゼル", en: "Buizel", type1: "みず", type2: "" },
  { id: "0419", name: "フローゼル", en: "Floatzel", type1: "みず", type2: "" },
  { id: "0420", name: "チェリンボ", en: "Cherubi", type1: "くさ", type2: "" },
  { id: "0421", name: "チェリム", en: "Cherrim", type1: "くさ", type2: "" },
  { id: "0422", name: "カラナクシ", en: "Shellos", type1: "みず", type2: "" },
  { id: "0423", name: "トリトドン", en: "Gastrodon", type1: "みず", type2: "じめ" },
  { id: "0424", name: "エテボース", en: "Ambipom", type1: "のま", type2: "" },
  { id: "0425", name: "フワンテ", en: "Drifloon", type1: "ごす", type2: "ひこ" },
  { id: "0426", name: "フワライド", en: "Drifblim", type1: "ごす", type2: "ひこ" },
  { id: "0427", name: "ミミロル", en: "Buneary", type1: "のま", type2: "" },
  { id: "0428", name: "ミミロップ", en: "Lopunny", type1: "のま", type2: "" },
  { id: "0429", name: "ムウマージ", en: "Mismagius", type1: "ごす", type2: "" },
  { id: "0430", name: "ドンカラス", en: "Honchkrow", type1: "あく", type2: "ひこ" },
  { id: "0431", name: "ニャルマー", en: "Glameow", type1: "のま", type2: "" },
  { id: "0432", name: "ブニャット", en: "Purugly", type1: "のま", type2: "" },
  { id: "0433", name: "リーシャン", en: "Chingling", type1: "えす", type2: "" },
  { id: "0434", name: "スカンプー", en: "Stunky", type1: "どく", type2: "あく" },
  { id: "0435", name: "スカタンク", en: "Skuntank", type1: "どく", type2: "あく" },
  { id: "0436", name: "ドーミラー", en: "Bronzor", type1: "はが", type2: "えす" },
  { id: "0437", name: "ドータクン", en: "Bronzong", type1: "はが", type2: "えす" },
  { id: "0438", name: "ウソハチ", en: "Bonsly", type1: "いわ", type2: "" },
  { id: "0439", name: "マネネ", en: "Mime Jr.", type1: "えす", type2: "ふぇ" },
  { id: "0440", name: "ピンプク", en: "Happiny", type1: "のま", type2: "" },
  { id: "0441", name: "ペラップ", en: "Chatot", type1: "のま", type2: "ひこ" },
  { id: "0442", name: "ミカルゲ", en: "Spiritomb", type1: "ごす", type2: "あく" },
  { id: "0443", name: "フカマル", en: "Gible", type1: "どら", type2: "じめ" },
  { id: "0444", name: "ガバイト", en: "Gabite", type1: "どら", type2: "じめ" },
  { id: "0445", name: "ガブリアス", en: "Garchomp", type1: "どら", type2: "じめ" },
  { id: "0446", name: "ゴンベ", en: "Munchlax", type1: "のま", type2: "" },
  { id: "0447", name: "リオル", en: "Riolu", type1: "かく", type2: "" },
  { id: "0448", name: "ルカリオ", en: "Lucario", type1: "かく", type2: "はが" },
  { id: "0449", name: "ヒポポタス", en: "Hippopotas", type1: "じめ", type2: "" },
  { id: "0450", name: "カバルドン", en: "Hippowdon", type1: "じめ", type2: "" },
  { id: "0451", name: "スコルピ", en: "Skorupi", type1: "どく", type2: "むし" },
  { id: "0452", name: "ドラピオン", en: "Drapion", type1: "どく", type2: "あく" },
  { id: "0453", name: "グレッグル", en: "Croagunk", type1: "どく", type2: "かく" },
  { id: "0454", name: "ドクロッグ", en: "Toxicroak", type1: "どく", type2: "かく" },
  { id: "0455", name: "マスキッパ", en: "Carnivine", type1: "くさ", type2: "" },
  { id: "0456", name: "ケイコウオ", en: "Finneon", type1: "みず", type2: "" },
  { id: "0457", name: "ネオラント", en: "Lumineon", type1: "みず", type2: "" },
  { id: "0458", name: "タマンタ", en: "Mantyke", type1: "みず", type2: "ひこ" },
  { id: "0459", name: "ユキカブリ", en: "Snover", type1: "くさ", type2: "こお" },
  { id: "0460", name: "ユキノオー", en: "Abomasnow", type1: "くさ", type2: "こお" },
  { id: "0461", name: "マニューラ", en: "Weavile", type1: "あく", type2: "こお" },
  { id: "0462", name: "ジバコイル", en: "Magnezone", type1: "でん", type2: "はが" },
  { id: "0463", name: "ベロベルト", en: "Lickilicky", type1: "のま", type2: "" },
  { id: "0464", name: "ドサイドン", en: "Rhyperior", type1: "じめ", type2: "いわ" },
  { id: "0465", name: "モジャンボ", en: "Tangrowth", type1: "くさ", type2: "" },
  { id: "0466", name: "エレキブル", en: "Electivire", type1: "でん", type2: "" },
  { id: "0467", name: "ブーバーン", en: "Magmortar", type1: "ほの", type2: "" },
  { id: "0468", name: "トゲキッス", en: "Togekiss", type1: "ふぇ", type2: "ひこ" },
  { id: "0469", name: "メガヤンマ", en: "Yanmega", type1: "むし", type2: "ひこ" },
  { id: "0470", name: "リーフィア", en: "Leafeon", type1: "くさ", type2: "" },
  { id: "0471", name: "グレイシア", en: "Glaceon", type1: "こお", type2: "" },
  { id: "0472", name: "グライオン", en: "Gliscor", type1: "じめ", type2: "ひこ" },
  { id: "0473", name: "マンムー", en: "Mamoswine", type1: "こお", type2: "じめ" },
  { id: "0474", name: "ポリゴンＺ", en: "Porygon-Z", type1: "のま", type2: "" },
  { id: "0475", name: "エルレイド", en: "Gallade", type1: "えす", type2: "かく" },
  { id: "0476", name: "ダイノーズ", en: "Probopass", type1: "いわ", type2: "はが" },
  { id: "0477", name: "ヨノワール", en: "Dusknoir", type1: "ごす", type2: "" },
  { id: "0478", name: "ユキメノコ", en: "Froslass", type1: "こお", type2: "ごす" },
  { id: "0479", sugata: "00", name: "ロトム", en: "Rotom", type1: "でん", type2: "ごす" },
  { id: "0479", sugata: "01", name: "ロトム(ヒート)", en: "Rotom", type1: "でん", type2: "ほの" },
  { id: "0479", sugata: "02", name: "ロトム(ウォッシュ)", en: "Rotom", type1: "でん", type2: "ひこ" },
  { id: "0479", sugata: "03", name: "ロトム(フロスト)", en: "Rotom", type1: "でん", type2: "こお" },
  { id: "0479", sugata: "04", name: "ロトム(スピン)", en: "Rotom", type1: "でん", type2: "みず" },
  { id: "0479", sugata: "05", name: "ロトム(カット)", en: "Rotom", type1: "でん", type2: "くさ" },
  { id: "0480", name: "ユクシー", en: "Uxie", type1: "えす", type2: "" },
  { id: "0481", name: "エムリット", en: "Mesprit", type1: "えす", type2: "" },
  { id: "0482", name: "アグノム", en: "Azelf", type1: "えす", type2: "" },
  { id: "0483", name: "ディアルガ", en: "Dialga", type1: "はが", type2: "どら" },
  { id: "0484", name: "パルキア", en: "Palkia", type1: "みず", type2: "どら" },
  { id: "0485", name: "ヒードラン", en: "Heatran", type1: "ほの", type2: "はが" },
  { id: "0486", name: "レジギガス", en: "Regigigas", type1: "のま", type2: "" },
  { id: "0487", name: "ギラティナ", en: "Giratina", type1: "ごす", type2: "どら" },
  { id: "0488", name: "クレセリア", en: "Cresselia", type1: "えす", type2: "" },
  { id: "0489", name: "フィオネ", en: "Phione", type1: "みず", type2: "" },
  { id: "0490", name: "マナフィ", en: "Manaphy", type1: "みず", type2: "" },
  { id: "0491", name: "ダークライ", en: "Darkrai", type1: "あく", type2: "" },
  { id: "0492", name: "シェイミ", en: "Shaymin", type1: "くさ", type2: "" },
  { id: "0493", name: "アルセウス", en: "Arceus", type1: "のま", type2: "" },
  { id: "0494", name: "ビクティニ", en: "Victini", type1: "えす", type2: "ほの" },
  { id: "0495", name: "ツタージャ", en: "Snivy", type1: "くさ", type2: "" },
  { id: "0496", name: "ジャノビー", en: "Servine", type1: "くさ", type2: "" },
  { id: "0497", name: "ジャローダ", en: "Serperior", type1: "くさ", type2: "" },
  { id: "0498", name: "ポカブ", en: "Tepig", type1: "ほの", type2: "" },
  { id: "0499", name: "チャオブー", en: "Pignite", type1: "ほの", type2: "かく" },
  { id: "0500", name: "エンブオー", en: "Emboar", type1: "ほの", type2: "かく" },
  { id: "0501", name: "ミジュマル", en: "Oshawott", type1: "みず", type2: "" },
  { id: "0502", name: "フタチマル", en: "Dewott", type1: "みず", type2: "" },
  { id: "0503", sugata: "00", name: "ダイケンキ", en: "Samurott", type1: "みず", type2: "" },
  { id: "0503", sugata: "01", name: "ダイケンキ(ヒスイ)", en: "Samurott", type1: "みず", type2: "あく" },
  { id: "0504", name: "ミネズミ", en: "Patrat", type1: "のま", type2: "" },
  { id: "0505", name: "ミルホッグ", en: "Watchog", type1: "のま", type2: "" },
  { id: "0506", name: "ヨーテリー", en: "Lillipup", type1: "のま", type2: "" },
  { id: "0507", name: "ハーデリア", en: "Herdier", type1: "のま", type2: "" },
  { id: "0508", name: "ムーランド", en: "Stoutland", type1: "のま", type2: "" },
  { id: "0509", name: "チョロネコ", en: "Purrloin", type1: "あく", type2: "" },
  { id: "0510", name: "レパルダス", en: "Liepard", type1: "あく", type2: "" },
  { id: "0511", name: "ヤナップ", en: "Pansage", type1: "くさ", type2: "" },
  { id: "0512", name: "ヤナッキー", en: "Simisage", type1: "くさ", type2: "" },
  { id: "0513", name: "バオップ", en: "Pansear", type1: "ほの", type2: "" },
  { id: "0514", name: "バオッキー", en: "Simisear", type1: "ほの", type2: "" },
  { id: "0515", name: "ヒヤップ", en: "Panpour", type1: "みず", type2: "" },
  { id: "0516", name: "ヒヤッキー", en: "Simipour", type1: "みず", type2: "" },
  { id: "0517", name: "ムンナ", en: "Munna", type1: "えす", type2: "" },
  { id: "0518", name: "ムシャーナ", en: "Musharna", type1: "えす", type2: "" },
  { id: "0519", name: "マメパト", en: "Pidove", type1: "のま", type2: "ひこ" },
  { id: "0520", name: "ハトーボー", en: "Tranquill", type1: "のま", type2: "ひこ" },
  { id: "0521", name: "ケンホロウ", en: "Unfezant", type1: "のま", type2: "ひこ" },
  { id: "0522", name: "シママ", en: "Blitzle", type1: "でん", type2: "" },
  { id: "0523", name: "ゼブライカ", en: "Zebstrika", type1: "でん", type2: "" },
  { id: "0524", name: "ダンゴロ", en: "Roggenrola", type1: "いわ", type2: "" },
  { id: "0525", name: "ガントル", en: "Boldore", type1: "いわ", type2: "" },
  { id: "0526", name: "ギガイアス", en: "Gigalith", type1: "いわ", type2: "" },
  { id: "0527", name: "コロモリ", en: "Woobat", type1: "えす", type2: "ひこ" },
  { id: "0528", name: "ココロモリ", en: "Swoobat", type1: "えす", type2: "ひこ" },
  { id: "0529", name: "モグリュー", en: "Drilbur", type1: "じめ", type2: "" },
  { id: "0530", name: "ドリュウズ", en: "Excadrill", type1: "じめ", type2: "はが" },
  { id: "0531", name: "タブンネ", en: "Audino", type1: "のま", type2: "" },
  { id: "0532", name: "ドッコラー", en: "Timburr", type1: "かく", type2: "" },
  { id: "0533", name: "ドテッコツ", en: "Gurdurr", type1: "かく", type2: "" },
  { id: "0534", name: "ローブシン", en: "Conkeldurr", type1: "かく", type2: "" },
  { id: "0535", name: "オタマロ", en: "Tympole", type1: "みず", type2: "" },
  { id: "0536", name: "ガマガル", en: "Palpitoad", type1: "みず", type2: "じめ" },
  { id: "0537", name: "ガマゲロゲ", en: "Seismitoad", type1: "みず", type2: "じめ" },
  { id: "0538", name: "ナゲキ", en: "Throh", type1: "かく", type2: "" },
  { id: "0539", name: "ダゲキ", en: "Sawk", type1: "かく", type2: "" },
  { id: "0540", name: "クルミル", en: "Sewaddle", type1: "むし", type2: "くさ" },
  { id: "0541", name: "クルマユ", en: "Swadloon", type1: "むし", type2: "くさ" },
  { id: "0542", name: "ハハコモリ", en: "Leavanny", type1: "むし", type2: "くさ" },
  { id: "0543", name: "フシデ", en: "Venipede", type1: "むし", type2: "どく" },
  { id: "0544", name: "ホイーガ", en: "Whirlipede", type1: "むし", type2: "どく" },
  { id: "0545", name: "ペンドラー", en: "Scolipede", type1: "むし", type2: "どく" },
  { id: "0546", name: "モンメン", en: "Cottonee", type1: "くさ", type2: "ふぇ" },
  { id: "0547", name: "エルフーン", en: "Whimsicott", type1: "くさ", type2: "ふぇ" },
  { id: "0548", name: "チュリネ", en: "Petilil", type1: "くさ", type2: "" },
  { id: "0549", sugata: "00", name: "ドレディア", en: "Lilligant", type1: "くさ", type2: "" },
  { id: "0549", sugata: "01", name: "ドレディア(ヒスイ)", en: "Lilligant", type1: "くさ", type2: "かく" },
  { id: "0550", sugata: "00", name: "バスラオ(あかすじ)", en: "Basculin", type1: "みず", type2: "" },
  { id: "0550", sugata: "01", name: "バスラオ(あおすじ)", en: "Basculin", type1: "みず", type2: "" },
  { id: "0550", sugata: "02", name: "バスラオ(しろすじ)", en: "Basculin", type1: "みず", type2: "" },
  { id: "0551", name: "メグロコ", en: "Sandile", type1: "じめ", type2: "あく" },
  { id: "0552", name: "ワルビル", en: "Krokorok", type1: "じめ", type2: "あく" },
  { id: "0553", name: "ワルビアル", en: "Krookodile", type1: "じめ", type2: "あく" },
  { id: "0554", sugata: "00", name: "ダルマッカ", en: "Darumaka", type1: "ほの", type2: "" },
  { id: "0554", sugata: "01", name: "ダルマッカ(ガラル)", en: "Darumaka", type1: "こお", type2: "" },
  { id: "0555", sugata: "00", name: "ヒヒダルマ", en: "Darmanitan", type1: "ほの", type2: "" },
  { id: "0555", sugata: "02", name: "ヒヒダルマ(ガラル)", en: "Darmanitan", type1: "こお", type2: "" },
  { id: "0556", name: "マラカッチ", en: "Maractus", type1: "くさ", type2: "" },
  { id: "0557", name: "イシズマイ", en: "Dwebble", type1: "むし", type2: "いわ" },
  { id: "0558", name: "イワパレス", en: "Crustle", type1: "むし", type2: "いわ" },
  { id: "0559", name: "ズルッグ", en: "Scraggy", type1: "あく", type2: "かく" },
  { id: "0560", name: "ズルズキン", en: "Scrafty", type1: "あく", type2: "かく" },
  { id: "0561", name: "シンボラー", en: "Sigilyph", type1: "えす", type2: "ひこ" },
  { id: "0562", sugata: "00", name: "デスマス", en: "Yamask", type1: "ごす", type2: "" },
  { id: "0562", sugata: "01", name: "デスマス(ガラル)", en: "Yamask", type1: "じめ", type2: "ごす" },
  { id: "0563", name: "デスカーン", en: "Cofagrigus", type1: "ごす", type2: "" },
  { id: "0564", name: "プロトーガ", en: "Tirtouga", type1: "みず", type2: "いわ" },
  { id: "0565", name: "アバゴーラ", en: "Carracosta", type1: "みず", type2: "いわ" },
  { id: "0566", name: "アーケン", en: "Archen", type1: "いわ", type2: "ひこ" },
  { id: "0567", name: "アーケオス", en: "Archeops", type1: "いわ", type2: "ひこ" },
  { id: "0568", name: "ヤブクロン", en: "Trubbish", type1: "どく", type2: "" },
  { id: "0569", name: "ダストダス", en: "Garbodor", type1: "どく", type2: "" },
  { id: "0570", sugata: "00", name: "ゾロア", en: "Zorua", type1: "あく", type2: "" },
  { id: "0570", sugata: "01", name: "ゾロア(ヒスイ)", en: "Zorua", type1: "のま", type2: "ごす" },
  { id: "0571", sugata: "00", name: "ゾロアーク", en: "Zoroark", type1: "あく", type2: "" },
  { id: "0571", sugata: "01", name: "ゾロアーク(ヒスイ)", en: "Zoroark", type1: "のま", type2: "ごす" },
  { id: "0572", name: "チラーミィ", en: "Minccino", type1: "のま", type2: "" },
  { id: "0573", name: "チラチーノ", en: "Cinccino", type1: "のま", type2: "" },
  { id: "0574", name: "ゴチム", en: "Gothita", type1: "えす", type2: "" },
  { id: "0575", name: "ゴチミル", en: "Gothorita", type1: "えす", type2: "" },
  { id: "0576", name: "ゴチルゼル", en: "Gothitelle", type1: "えす", type2: "" },
  { id: "0577", name: "ユニラン", en: "Solosis", type1: "えす", type2: "" },
  { id: "0578", name: "ダブラン", en: "Duosion", type1: "えす", type2: "" },
  { id: "0579", name: "ランクルス", en: "Reuniclus", type1: "えす", type2: "" },
  { id: "0580", name: "コアルヒー", en: "Ducklett", type1: "みず", type2: "ひこ" },
  { id: "0581", name: "スワンナ", en: "Swanna", type1: "みず", type2: "ひこ" },
  { id: "0582", name: "バニプッチ", en: "Vanillite", type1: "こお", type2: "" },
  { id: "0583", name: "バニリッチ", en: "Vanillish", type1: "こお", type2: "" },
  { id: "0584", name: "バイバニラ", en: "Vanilluxe", type1: "こお", type2: "" },
  { id: "0585", name: "シキジカ", en: "Deerling", type1: "のま", type2: "くさ" },
  { id: "0586", name: "メブキジカ", en: "Sawsbuck", type1: "のま", type2: "くさ" },
  { id: "0587", name: "エモンガ", en: "Emolga", type1: "でん", type2: "ひこ" },
  { id: "0588", name: "カブルモ", en: "Karrablast", type1: "むし", type2: "" },
  { id: "0589", name: "シュバルゴ", en: "Escavalier", type1: "むし", type2: "はが" },
  { id: "0590", name: "タマゲタケ", en: "Foongus", type1: "くさ", type2: "どく" },
  { id: "0591", name: "モロバレル", en: "Amoonguss", type1: "くさ", type2: "どく" },
  { id: "0592", name: "プルリル", en: "Frillish", type1: "みず", type2: "ごす" },
  { id: "0593", name: "ブルンゲル", en: "Jellicent", type1: "みず", type2: "ごす" },
  { id: "0594", name: "ママンボウ", en: "Alomomola", type1: "みず", type2: "" },
  { id: "0595", name: "バチュル", en: "Joltik", type1: "むし", type2: "でん" },
  { id: "0596", name: "デンチュラ", en: "Galvantula", type1: "むし", type2: "でん" },
  { id: "0597", name: "テッシード", en: "Ferroseed", type1: "くさ", type2: "はが" },
  { id: "0598", name: "ナットレイ", en: "Ferrothorn", type1: "くさ", type2: "はが" },
  { id: "0599", name: "ギアル", en: "Klink", type1: "はが", type2: "" },
  { id: "0600", name: "ギギアル", en: "Klang", type1: "はが", type2: "" },
  { id: "0601", name: "ギギギアル", en: "Klinklang", type1: "はが", type2: "" },
  { id: "0602", name: "シビシラス", en: "Tynamo", type1: "でん", type2: "" },
  { id: "0603", name: "シビビール", en: "Eelektrik", type1: "でん", type2: "" },
  { id: "0604", name: "シビルドン", en: "Eelektross", type1: "でん", type2: "" },
  { id: "0605", name: "リグレー", en: "Elgyem", type1: "えす", type2: "" },
  { id: "0606", name: "オーベム", en: "Beheeyem", type1: "えす", type2: "" },
  { id: "0607", name: "ヒトモシ", en: "Litwick", type1: "ごす", type2: "ほの" },
  { id: "0608", name: "ランプラー", en: "Lampent", type1: "ごす", type2: "ほの" },
  { id: "0609", name: "シャンデラ", en: "Chandelure", type1: "ごす", type2: "ほの" },
  { id: "0610", name: "キバゴ", en: "Axew", type1: "どら", type2: "" },
  { id: "0611", name: "オノンド", en: "Fraxure", type1: "どら", type2: "" },
  { id: "0612", name: "オノノクス", en: "Haxorus", type1: "どら", type2: "" },
  { id: "0613", name: "クマシュン", en: "Cubchoo", type1: "こお", type2: "" },
  { id: "0614", name: "ツンベアー", en: "Beartic", type1: "こお", type2: "" },
  { id: "0615", name: "フリージオ", en: "Cryogonal", type1: "こお", type2: "" },
  { id: "0616", name: "チョボマキ", en: "Shelmet", type1: "むし", type2: "" },
  { id: "0617", name: "アギルダー", en: "Accelgor", type1: "むし", type2: "" },
  { id: "0618", sugata: "00", name: "マッギョ", en: "Stunfisk", type1: "じめ", type2: "でん" },
  { id: "0618", sugata: "01", name: "マッギョ(ガラル)", en: "Stunfisk", type1: "じめ", type2: "はが" },
  { id: "0619", name: "コジョフー", en: "Mienfoo", type1: "かく", type2: "" },
  { id: "0620", name: "コジョンド", en: "Mienshao", type1: "かく", type2: "" },
  { id: "0621", name: "クリムガン", en: "Druddigon", type1: "どら", type2: "" },
  { id: "0622", name: "ゴビット", en: "Golett", type1: "じめ", type2: "ごす" },
  { id: "0623", name: "ゴルーグ", en: "Golurk", type1: "じめ", type2: "ごす" },
  { id: "0624", name: "コマタナ", en: "Pawniard", type1: "あく", type2: "はが" },
  { id: "0625", name: "キリキザン", en: "Bisharp", type1: "あく", type2: "はが" },
  { id: "0626", name: "バッフロン", en: "Bouffalant", type1: "のま", type2: "" },
  { id: "0627", name: "ワシボン", en: "Rufflet", type1: "のま", type2: "ひこ" },
  { id: "0628", sugata: "00", name: "ウォーグル", en: "Braviary", type1: "のま", type2: "ひこ" },
  { id: "0628", sugata: "01", name: "ウォーグル(ヒスイ)", en: "Braviary", type1: "えす", type2: "ひこ" },
  { id: "0629", name: "バルチャイ", en: "Vullaby", type1: "あく", type2: "ひこ" },
  { id: "0630", name: "バルジーナ", en: "Mandibuzz", type1: "あく", type2: "ひこ" },
  { id: "0631", name: "クイタラン", en: "Heatmor", type1: "ほの", type2: "" },
  { id: "0632", name: "アイアント", en: "Durant", type1: "むし", type2: "はが" },
  { id: "0633", name: "モノズ", en: "Deino", type1: "あく", type2: "どら" },
  { id: "0634", name: "ジヘッド", en: "Zweilous", type1: "あく", type2: "どら" },
  { id: "0635", name: "サザンドラ", en: "Hydreigon", type1: "あく", type2: "どら" },
  { id: "0636", name: "メラルバ", en: "Larvesta", type1: "むし", type2: "ほの" },
  { id: "0637", name: "ウルガモス", en: "Volcarona", type1: "むし", type2: "ほの" },
  { id: "0638", name: "コバルオン", en: "Cobalion", type1: "はが", type2: "かく" },
  { id: "0639", name: "テラキオン", en: "Terrakion", type1: "いわ", type2: "かく" },
  { id: "0640", name: "ビリジオン", en: "Virizion", type1: "くさ", type2: "かく" },
  { id: "0641", sugata: "00", name: "トルネロス(けしん)", en: "Tornadus", type1: "ひこ", type2: "" },
  { id: "0641", sugata: "01", name: "トルネロス(れいじゅう)", en: "Tornadus", type1: "ひこ", type2: "" },
  { id: "0642", sugata: "00", name: "ボルトロス(けしん)", en: "Thundurus", type1: "でん", type2: "ひこ" },
  { id: "0642", sugata: "01", name: "ボルトロス(れいじゅう)", en: "Thundurus", type1: "でん", type2: "ひこ" },
  { id: "0643", name: "レシラム", en: "Reshiram", type1: "どら", type2: "ほの" },
  { id: "0644", name: "ゼクロム", en: "Zekrom", type1: "どら", type2: "でん" },
  { id: "0645", sugata: "00", name: "ランドロス(けしん)", en: "Landorus", type1: "じめ", type2: "ひこ" },
  { id: "0645", sugata: "01", name: "ランドロス(れいじゅう)", en: "Landorus", type1: "じめ", type2: "ひこ" },
  { id: "0646", sugata: "00", name: "キュレム", en: "Kyurem", type1: "どら", type2: "こお" },
  { id: "0646", sugata: "01", name: "キュレム(ホワイト)", en: "Kyurem", type1: "どら", type2: "こお" },
  { id: "0646", sugata: "02", name: "キュレム(ブラック)", en: "Kyurem", type1: "どら", type2: "こお" },
  { id: "0647", sugata: "00", name: "ケルディオ(いつも)", en: "Keldeo", type1: "みず", type2: "かく" },
  { id: "0647", sugata: "01", name: "ケルディオ(かくご)", en: "Keldeo", type1: "みず", type2: "かく" },
  { id: "0648", sugata: "00", name: "メロエッタ(ボイス)", en: "Meloetta", type1: "のま", type2: "えす" },
  { id: "0648", sugata: "01", name: "メロエッタ(ステップ)", en: "Meloetta", type1: "のま", type2: "かく" },
  { id: "0649", name: "ゲノセクト", en: "Genesect", type1: "むし", type2: "はが" },
  { id: "0650", name: "ハリマロン", en: "Chespin", type1: "くさ", type2: "" },
  { id: "0651", name: "ハリボーグ", en: "Quilladin", type1: "くさ", type2: "" },
  { id: "0652", name: "ブリガロン", en: "Chesnaught", type1: "くさ", type2: "かく" },
  { id: "0653", name: "フォッコ", en: "Fennekin", type1: "ほの", type2: "" },
  { id: "0654", name: "テールナー", en: "Braixen", type1: "ほの", type2: "" },
  { id: "0655", name: "マフォクシー", en: "Delphox", type1: "ほの", type2: "えす" },
  { id: "0656", name: "ケロマツ", en: "Froakie", type1: "みず", type2: "" },
  { id: "0657", name: "ゲコガシラ", en: "Frogadier", type1: "みず", type2: "" },
  { id: "0658", sugata: "00", name: "ゲッコウガ", en: "Greninja", type1: "みず", type2: "あく" },
  { id: "0658", sugata: "02", name: "ゲッコウガ(サトシ)", en: "Greninja", type1: "みず", type2: "あく" },
  { id: "0659", name: "ホルビー", en: "Bunnelby", type1: "のま", type2: "" },
  { id: "0660", name: "ホルード", en: "Diggersby", type1: "のま", type2: "じめ" },
  { id: "0661", name: "ヤヤコマ", en: "Fletchling", type1: "のま", type2: "ひこ" },
  { id: "0662", name: "ヒノヤコマ", en: "Fletchinder", type1: "ほの", type2: "ひこ" },
  { id: "0663", name: "ファイアロー", en: "Talonflame", type1: "ほの", type2: "ひこ" },
  { id: "0664", name: "コフキムシ", en: "Scatterbug", type1: "むし", type2: "" },
  { id: "0665", name: "コフーライ", en: "Spewpa", type1: "むし", type2: "" },
  { id: "0666", sugata: "00", name: "ビビヨン(ひょうせつ)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "01", name: "ビビヨン(ゆきぐに)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "02", name: "ビビヨン(せつげん)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "03", name: "ビビヨン(たいりく)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "04", name: "ビビヨン(ていえん)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "05", name: "ビビヨン(みやび)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "06", name: "ビビヨン(はなぞの)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "07", name: "ビビヨン(モダン)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "08", name: "ビビヨン(マリン)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "09", name: "ビビヨン(ぐんとう)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "10", name: "ビビヨン(こうや)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "11", name: "ビビヨン(さじん)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "12", name: "ビビヨン(たいが)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "13", name: "ビビヨン(スコール)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "14", name: "ビビヨン(サバンナ)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "15", name: "ビビヨン(たいよう)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "16", name: "ビビヨン(オーシャン)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "17", name: "ビビヨン(ジャングル)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "18", name: "ビビヨン(ファンシー)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0666", sugata: "19", name: "ビビヨン(ボール)", en: "Vivillon", type1: "むし", type2: "ひこ" },
  { id: "0667", name: "シシコ", en: "Litleo", type1: "ほの", type2: "のま" },
  { id: "0668", name: "カエンジシ", en: "Pyroar", type1: "ほの", type2: "のま" },
  { id: "0669", name: "フラベベ", en: "Flabebe", type1: "ふぇ", type2: "" },
  { id: "0670", name: "フラエッテ", en: "Floette", type1: "ふぇ", type2: "" },
  { id: "0671", name: "フラージェス", en: "Florges", type1: "ふぇ", type2: "" },
  { id: "0672", name: "メェークル", en: "Skiddo", type1: "くさ", type2: "" },
  { id: "0673", name: "ゴーゴート", en: "Gogoat", type1: "くさ", type2: "" },
  { id: "0674", name: "ヤンチャム", en: "Pancham", type1: "かく", type2: "" },
  { id: "0675", name: "ゴロンダ", en: "Pangoro", type1: "かく", type2: "あく" },
  { id: "0676", name: "トリミアン", en: "Furfrou", type1: "のま", type2: "" },
  { id: "0677", name: "ニャスパー", en: "Espurr", type1: "えす", type2: "" },
  { id: "0678", sugata: "00", name: "ニャオニクス(♂)", en: "Meowstic", type1: "えす", type2: "" },
  { id: "0678", sugata: "01", name: "ニャオニクス(♀)", en: "Meowstic", type1: "えす", type2: "" },
  { id: "0679", name: "ヒトツキ", en: "Honedge", type1: "はが", type2: "ごす" },
  { id: "0680", name: "ニダンギル", en: "Doublade", type1: "はが", type2: "ごす" },
  { id: "0681", name: "ギルガルド", en: "Aegislash", type1: "はが", type2: "ごす" },
  { id: "0682", name: "シュシュプ", en: "Spritzee", type1: "ふぇ", type2: "" },
  { id: "0683", name: "フレフワン", en: "Aromatisse", type1: "ふぇ", type2: "" },
  { id: "0684", name: "ペロッパフ", en: "Swirlix", type1: "ふぇ", type2: "" },
  { id: "0685", name: "ペロリーム", en: "Slurpuff", type1: "ふぇ", type2: "" },
  { id: "0686", name: "マーイーカ", en: "Inkay", type1: "あく", type2: "えす" },
  { id: "0687", name: "カラマネロ", en: "Malamar", type1: "あく", type2: "えす" },
  { id: "0688", name: "カメテテ", en: "Binacle", type1: "いわ", type2: "みず" },
  { id: "0689", name: "ガメノデス", en: "Barbaracle", type1: "いわ", type2: "みず" },
  { id: "0690", name: "クズモー", en: "Skrelp", type1: "どく", type2: "みず" },
  { id: "0691", name: "ドラミドロ", en: "Dragalge", type1: "どく", type2: "どら" },
  { id: "0692", name: "ウデッポウ", en: "Clauncher", type1: "みず", type2: "" },
  { id: "0693", name: "ブロスター", en: "Clawitzer", type1: "みず", type2: "" },
  { id: "0694", name: "エリキテル", en: "Helioptile", type1: "でん", type2: "のま" },
  { id: "0695", name: "エレザード", en: "Heliolisk", type1: "でん", type2: "のま" },
  { id: "0696", name: "チゴラス", en: "Tyrunt", type1: "いわ", type2: "どら" },
  { id: "0697", name: "ガチゴラス", en: "Tyrantrum", type1: "いわ", type2: "どら" },
  { id: "0698", name: "アマルス", en: "Amaura", type1: "いわ", type2: "こお" },
  { id: "0699", name: "アマルルガ", en: "Aurorus", type1: "いわ", type2: "こお" },
  { id: "0700", name: "ニンフィア", en: "Sylveon", type1: "ふぇ", type2: "" },
  { id: "0701", name: "ルチャブル", en: "Hawlucha", type1: "かく", type2: "ひこ" },
  { id: "0702", name: "デデンネ", en: "Dedenne", type1: "でん", type2: "ふぇ" },
  { id: "0703", name: "メレシー", en: "Carbink", type1: "いわ", type2: "ふぇ" },
  { id: "0704", name: "ヌメラ", en: "Goomy", type1: "どら", type2: "" },
  { id: "0705", sugata: "00", name: "ヌメイル", en: "Sliggoo", type1: "どら", type2: "" },
  { id: "0705", sugata: "01", name: "ヌメイル(ヒスイ)", en: "Sliggoo", type1: "はが", type2: "どら" },
  { id: "0706", sugata: "00", name: "ヌメルゴン", en: "Goodra", type1: "どら", type2: "" },
  { id: "0706", sugata: "01", name: "ヌメルゴン(ヒスイ)", en: "Goodra", type1: "はが", type2: "どら" },
  { id: "0707", name: "クレッフィ", en: "Klefki", type1: "はが", type2: "ふぇ" },
  { id: "0708", name: "ボクレー", en: "Phantump", type1: "ごす", type2: "くさ" },
  { id: "0709", name: "オーロット", en: "Trevenant", type1: "ごす", type2: "くさ" },
  { id: "0710", sugata: "00", name: "バケッチャ(ふつう)", en: "Pumpkaboo", type1: "ごす", type2: "くさ" },
  { id: "0710", sugata: "01", name: "バケッチャ(ちいさい)", en: "Pumpkaboo", type1: "ごす", type2: "くさ" },
  { id: "0710", sugata: "02", name: "バケッチャ(おおきい)", en: "Pumpkaboo", type1: "ごす", type2: "くさ" },
  { id: "0710", sugata: "03", name: "バケッチャ(とくだい)", en: "Pumpkaboo", type1: "ごす", type2: "くさ" },
  { id: "0711", sugata: "00", name: "パンプジン(ふつう)", en: "Gourgeist", type1: "ごす", type2: "くさ" },
  { id: "0711", sugata: "01", name: "パンプジン(ちいさい)", en: "Gourgeist", type1: "ごす", type2: "くさ" },
  { id: "0711", sugata: "02", name: "パンプジン(おおきい)", en: "Gourgeist", type1: "ごす", type2: "くさ" },
  { id: "0711", sugata: "03", name: "パンプジン(とくだい)", en: "Gourgeist", type1: "ごす", type2: "くさ" },
  { id: "0712", name: "カチコール", en: "Bergmite", type1: "こお", type2: "" },
  { id: "0713", sugata: "00", name: "クレベース", en: "Avalugg", type1: "こお", type2: "" },
  { id: "0713", sugata: "01", name: "クレベース(ヒスイ)", en: "Avalugg", type1: "こお", type2: "いわ" },
  { id: "0714", name: "オンバット", en: "Noibat", type1: "ひこ", type2: "どら" },
  { id: "0715", name: "オンバーン", en: "Noivern", type1: "ひこ", type2: "どら" },
  { id: "0716", name: "ゼルネアス", en: "Xerneas", type1: "ふぇ", type2: "" },
  { id: "0717", name: "イベルタル", en: "Yveltal", type1: "あく", type2: "ひこ" },
  { id: "0718", sugata: "00", name: "ジガルデ(５０％)", en: "Zygarde", type1: "どら", type2: "じめ" },
  { id: "0718", sugata: "01", name: "ジガルデ(１０％)", en: "Zygarde", type1: "どら", type2: "じめ" },
  { id: "0719", name: "ディアンシー", en: "Diancie", type1: "いわ", type2: "ふぇ" },
  { id: "0720", name: "フーパ", en: "Hoopa", type1: "えす", type2: "ごす" },
  { id: "0721", name: "ボルケニオン", en: "Volcanion", type1: "ほの", type2: "みず" },
  { id: "0722", name: "モクロー", en: "Rowlet", type1: "くさ", type2: "ひこ" },
  { id: "0723", name: "フクスロー", en: "Dartrix", type1: "くさ", type2: "ひこ" },
  { id: "0724", sugata: "00", name: "ジュナイパー", en: "Decidueye", type1: "くさ", type2: "ごす" },
  { id: "0724", sugata: "01", name: "ジュナイパー(ヒスイ)", en: "Decidueye", type1: "くさ", type2: "かく" },
  { id: "0725", name: "ニャビー", en: "Litten", type1: "ほの", type2: "" },
  { id: "0726", name: "ニャヒート", en: "Torracat", type1: "ほの", type2: "" },
  { id: "0727", name: "ガオガエン", en: "Incineroar", type1: "ほの", type2: "あく" },
  { id: "0728", name: "アシマリ", en: "Popplio", type1: "みず", type2: "" },
  { id: "0729", name: "オシャマリ", en: "Brionne", type1: "みず", type2: "" },
  { id: "0730", name: "アシレーヌ", en: "Primarina", type1: "みず", type2: "ふぇ" },
  { id: "0731", name: "ツツケラ", en: "Pikipek", type1: "のま", type2: "ひこ" },
  { id: "0732", name: "ケララッパ", en: "Trumbeak", type1: "のま", type2: "ひこ" },
  { id: "0733", name: "ドデカバシ", en: "Toucannon", type1: "のま", type2: "ひこ" },
  { id: "0734", name: "ヤングース", en: "Yungoos", type1: "のま", type2: "" },
  { id: "0735", name: "デカグース", en: "Gumshoos", type1: "のま", type2: "" },
  { id: "0736", name: "アゴジムシ", en: "Grubbin", type1: "むし", type2: "" },
  { id: "0737", name: "デンヂムシ", en: "Charjabug", type1: "むし", type2: "でん" },
  { id: "0738", name: "クワガノン", en: "Vikavolt", type1: "むし", type2: "でん" },
  { id: "0739", name: "マケンカニ", en: "Crabrawler", type1: "かく", type2: "" },
  { id: "0740", name: "ケケンカニ", en: "Crabominable", type1: "かく", type2: "こお" },
  { id: "0741", sugata: "00", name: "オドリドリ(めらめら)", en: "Oricorio", type1: "ほの", type2: "ひこ" },
  { id: "0741", sugata: "01", name: "オドリドリ(ぱちぱち)", en: "Oricorio", type1: "でん", type2: "ひこ" },
  { id: "0741", sugata: "02", name: "オドリドリ(ふらふら)", en: "Oricorio", type1: "えす", type2: "ひこ" },
  { id: "0741", sugata: "03", name: "オドリドリ(まいまい)", en: "Oricorio", type1: "ごす", type2: "ひこ" },
  { id: "0742", name: "アブリー", en: "Cutiefly", type1: "むし", type2: "ふぇ" },
  { id: "0743", name: "アブリボン", en: "Ribombee", type1: "むし", type2: "ふぇ" },
  { id: "0744", name: "イワンコ", en: "Rockruff", type1: "いわ", type2: "" },
  { id: "0745", sugata: "00", name: "ルガルガン(まひる)", en: "Lycanroc", type1: "いわ", type2: "" },
  { id: "0745", sugata: "01", name: "ルガルガン(まよなか)", en: "Lycanroc", type1: "いわ", type2: "" },
  { id: "0745", sugata: "02", name: "ルガルガン(たそがれ)", en: "Lycanroc", type1: "いわ", type2: "" },
  { id: "0746", name: "ヨワシ", en: "Wishiwashi", type1: "みず", type2: "" },
  { id: "0747", name: "ヒドイデ", en: "Mareanie", type1: "どく", type2: "みず" },
  { id: "0748", name: "ドヒドイデ", en: "Toxapex", type1: "どく", type2: "みず" },
  { id: "0749", name: "ドロバンコ", en: "Mudbray", type1: "じめ", type2: "" },
  { id: "0750", name: "バンバドロ", en: "Mudsdale", type1: "じめ", type2: "" },
  { id: "0751", name: "シズクモ", en: "Dewpider", type1: "みず", type2: "むし" },
  { id: "0752", name: "オニシズクモ", en: "Araquanid", type1: "みず", type2: "むし" },
  { id: "0753", name: "カリキリ", en: "Fomantis", type1: "くさ", type2: "" },
  { id: "0754", name: "ラランテス", en: "Lurantis", type1: "くさ", type2: "" },
  { id: "0755", name: "ネマシュ", en: "Morelull", type1: "くさ", type2: "ふぇ" },
  { id: "0756", name: "マシェード", en: "Shiinotic", type1: "くさ", type2: "ふぇ" },
  { id: "0757", name: "ヤトウモリ", en: "Salandit", type1: "どく", type2: "ほの" },
  { id: "0758", name: "エンニュート", en: "Salazzle", type1: "どく", type2: "ほの" },
  { id: "0759", name: "ヌイコグマ", en: "Stufful", type1: "のま", type2: "かく" },
  { id: "0760", name: "キテルグマ", en: "Bewear", type1: "のま", type2: "かく" },
  { id: "0761", name: "アマカジ", en: "Bounsweet", type1: "くさ", type2: "" },
  { id: "0762", name: "アママイコ", en: "Steenee", type1: "くさ", type2: "" },
  { id: "0763", name: "アマージョ", en: "Tsareena", type1: "くさ", type2: "" },
  { id: "0764", name: "キュワワー", en: "Comfey", type1: "ふぇ", type2: "" },
  { id: "0765", name: "ヤレユータン", en: "Oranguru", type1: "のま", type2: "えす" },
  { id: "0766", name: "ナゲツケサル", en: "Passimian", type1: "かく", type2: "" },
  { id: "0767", name: "コソクムシ", en: "Wimpod", type1: "むし", type2: "みず" },
  { id: "0768", name: "グソクムシャ", en: "Golisopod", type1: "むし", type2: "みず" },
  { id: "0769", name: "スナバァ", en: "Sandygast", type1: "ごす", type2: "じめ" },
  { id: "0770", name: "シロデスナ", en: "Palossand", type1: "ごす", type2: "じめ" },
  { id: "0771", name: "ナマコブシ", en: "Pyukumuku", type1: "みず", type2: "" },
  { id: "0772", name: "タイプ：ヌル", en: "Type: Null", type1: "のま", type2: "" },
  { id: "0773", name: "シルヴァディ", en: "Silvally", type1: "のま", type2: "" },
  { id: "0774", name: "メテノ", en: "Minior", type1: "いわ", type2: "ひこ" },
  { id: "0775", name: "ネッコアラ", en: "Komala", type1: "のま", type2: "" },
  { id: "0776", name: "バクガメス", en: "Turtonator", type1: "ほの", type2: "どら" },
  { id: "0777", name: "トゲデマル", en: "Togedemaru", type1: "でん", type2: "はが" },
  { id: "0778", name: "ミミッキュ", en: "Mimikyu", type1: "ごす", type2: "ふぇ" },
  { id: "0779", name: "ハギギシリ", en: "Bruxish", type1: "みず", type2: "えす" },
  { id: "0780", name: "ジジーロン", en: "Drampa", type1: "のま", type2: "どら" },
  { id: "0781", name: "ダダリン", en: "Dhelmise", type1: "ごす", type2: "くさ" },
  { id: "0782", name: "ジャラコ", en: "Jangmo-o", type1: "どら", type2: "" },
  { id: "0783", name: "ジャランゴ", en: "Hakamo-o", type1: "どら", type2: "かく" },
  { id: "0784", name: "ジャラランガ", en: "Kommo-o", type1: "どら", type2: "かく" },
  { id: "0785", name: "カプ・コケコ", en: "Tapu Koko", type1: "でん", type2: "ふぇ" },
  { id: "0786", name: "カプ・テテフ", en: "Tapu Lele", type1: "えす", type2: "ふぇ" },
  { id: "0787", name: "カプ・ブルル", en: "Tapu Bulu", type1: "くさ", type2: "ふぇ" },
  { id: "0788", name: "カプ・レヒレ", en: "Tapu Fini", type1: "みず", type2: "ふぇ" },
  { id: "0789", name: "コスモッグ", en: "Cosmog", type1: "えす", type2: "" },
  { id: "0790", name: "コスモウム", en: "Cosmoem", type1: "えす", type2: "" },
  { id: "0791", name: "ソルガレオ", en: "Solgaleo", type1: "えす", type2: "はが" },
  { id: "0792", name: "ルナアーラ", en: "Lunala", type1: "えす", type2: "ごす" },
  { id: "0793", name: "ウツロイド", en: "Nihilego", type1: "いわ", type2: "どく" },
  { id: "0794", name: "マッシブーン", en: "Buzzwole", type1: "むし", type2: "かく" },
  { id: "0795", name: "フェローチェ", en: "Pheromosa", type1: "むし", type2: "かく" },
  { id: "0796", name: "デンジュモク", en: "Xurkitree", type1: "でん", type2: "" },
  { id: "0797", name: "テッカグヤ", en: "Celesteela", type1: "はが", type2: "ひこ" },
  { id: "0798", name: "カミツルギ", en: "Kartana", type1: "くさ", type2: "はが" },
  { id: "0799", name: "アクジキング", en: "Guzzlord", type1: "あく", type2: "どら" },
  { id: "0800", sugata: "00", name: "ネクロズマ", en: "Necrozma", type1: "えす", type2: "" },
  { id: "0800", sugata: "01", name: "ネクロズマ(たそがれ)", en: "Necrozma", type1: "えす", type2: "はが" },
  { id: "0800", sugata: "02", name: "ネクロズマ(あかつき)", en: "Necrozma", type1: "えす", type2: "ごす" },
  { id: "0801", name: "マギアナ", en: "Magearna", type1: "はが", type2: "ふぇ" },
  { id: "0802", name: "マーシャドー", en: "Marshadow", type1: "かく", type2: "ごす" },
  { id: "0803", name: "ベベノム", en: "Poipole", type1: "どく", type2: "" },
  { id: "0804", name: "アーゴヨン", en: "Naganadel", type1: "どく", type2: "どら" },
  { id: "0805", name: "ツンデツンデ", en: "Stakataka", type1: "いわ", type2: "はが" },
  { id: "0806", name: "ズガドーン", en: "Blacephalon", type1: "ほの", type2: "ごす" },
  { id: "0807", name: "ゼラオラ", en: "Zeraora", type1: "でん", type2: "" },
  { id: "0808", name: "メルタン", en: "Meltan", type1: "はが", type2: "" },
  { id: "0809", name: "メルメタル", en: "Melmetal", type1: "はが", type2: "" },
  { id: "0810", name: "サルノリ", en: "Grookey", type1: "くさ", type2: "" },
  { id: "0811", name: "バチンキー", en: "Thwackey", type1: "くさ", type2: "" },
  { id: "0812", name: "ゴリランダー", en: "Rillaboom", type1: "くさ", type2: "" },
  { id: "0813", name: "ヒバニー", en: "Scorbunny", type1: "ほの", type2: "" },
  { id: "0814", name: "ラビフット", en: "Raboot", type1: "ほの", type2: "" },
  { id: "0815", name: "エースバーン", en: "Cinderace", type1: "ほの", type2: "" },
  { id: "0816", name: "メッソン", en: "Sobble", type1: "みず", type2: "" },
  { id: "0817", name: "ジメレオン", en: "Drizzile", type1: "みず", type2: "" },
  { id: "0818", name: "インテレオン", en: "Inteleon", type1: "みず", type2: "" },
  { id: "0819", name: "ホシガリス", en: "Skwovet", type1: "のま", type2: "" },
  { id: "0820", name: "ヨクバリス", en: "Greedent", type1: "のま", type2: "" },
  { id: "0821", name: "ココガラ", en: "Rookidee", type1: "ひこ", type2: "" },
  { id: "0822", name: "アオガラス", en: "Corvisquire", type1: "ひこ", type2: "" },
  { id: "0823", name: "アーマーガア", en: "Corviknight", type1: "ひこ", type2: "はが" },
  { id: "0824", name: "サッチムシ", en: "Blipbug", type1: "むし", type2: "" },
  { id: "0825", name: "レドームシ", en: "Dottler", type1: "むし", type2: "えす" },
  { id: "0826", name: "イオルブ", en: "Orbeetle", type1: "むし", type2: "えす" },
  { id: "0827", name: "クスネ", en: "Nickit", type1: "あく", type2: "" },
  { id: "0828", name: "フォクスライ", en: "Thievul", type1: "あく", type2: "" },
  { id: "0829", name: "ヒメンカ", en: "Gossifleur", type1: "くさ", type2: "" },
  { id: "0830", name: "ワタシラガ", en: "Eldegoss", type1: "くさ", type2: "" },
  { id: "0831", name: "ウールー", en: "Wooloo", type1: "のま", type2: "" },
  { id: "0832", name: "バイウールー", en: "Dubwool", type1: "のま", type2: "" },
  { id: "0833", name: "カムカメ", en: "Chewtle", type1: "みず", type2: "" },
  { id: "0834", name: "カジリガメ", en: "Drednaw", type1: "みず", type2: "いわ" },
  { id: "0835", name: "ワンパチ", en: "Yamper", type1: "でん", type2: "" },
  { id: "0836", name: "パルスワン", en: "Boltund", type1: "でん", type2: "" },
  { id: "0837", name: "タンドン", en: "Rolycoly", type1: "いわ", type2: "" },
  { id: "0838", name: "トロッゴン", en: "Carkol", type1: "いわ", type2: "ほの" },
  { id: "0839", name: "セキタンザン", en: "Coalossal", type1: "いわ", type2: "ほの" },
  { id: "0840", name: "カジッチュ", en: "Applin", type1: "くさ", type2: "どら" },
  { id: "0841", name: "アップリュー", en: "Flapple", type1: "くさ", type2: "どら" },
  { id: "0842", name: "タルップル", en: "Appletun", type1: "くさ", type2: "どら" },
  { id: "0843", name: "スナヘビ", en: "Silicobra", type1: "じめ", type2: "" },
  { id: "0844", name: "サダイジャ", en: "Sandaconda", type1: "じめ", type2: "" },
  { id: "0845", name: "ウッウ", en: "Cramorant", type1: "ひこ", type2: "みず" },
  { id: "0846", name: "サシカマス", en: "Arrokuda", type1: "みず", type2: "" },
  { id: "0847", name: "カマスジョー", en: "Barraskewda", type1: "みず", type2: "" },
  { id: "0848", name: "エレズン", en: "Toxel", type1: "でん", type2: "どく" },
  { id: "0849", sugata: "00", name: "ストリンダー(ハイ)", en: "Toxtricity", type1: "でん", type2: "どく" },
  { id: "0849", sugata: "01", name: "ストリンダー(ロー)", en: "Toxtricity", type1: "でん", type2: "どく" },
  { id: "0850", name: "ヤクデ", en: "Sizzlipede", type1: "ほの", type2: "むし" },
  { id: "0851", name: "マルヤクデ", en: "Centiskorch", type1: "ほの", type2: "むし" },
  { id: "0852", name: "タタッコ", en: "Clobbopus", type1: "かく", type2: "" },
  { id: "0853", name: "オトスパス", en: "Grapploct", type1: "かく", type2: "" },
  { id: "0854", name: "ヤバチャ", en: "Sinistea", type1: "ごす", type2: "" },
  { id: "0855", name: "ポットデス", en: "Polteageist", type1: "ごす", type2: "" },
  { id: "0856", name: "ミブリム", en: "Hatenna", type1: "えす", type2: "" },
  { id: "0857", name: "テブリム", en: "Hattrem", type1: "えす", type2: "" },
  { id: "0858", name: "ブリムオン", en: "Hatterene", type1: "えす", type2: "ふぇ" },
  { id: "0859", name: "ベロバー", en: "Impidimp", type1: "あく", type2: "ふぇ" },
  { id: "0860", name: "ギモー", en: "Morgrem", type1: "あく", type2: "ふぇ" },
  { id: "0861", name: "オーロンゲ", en: "Grimmsnarl", type1: "あく", type2: "ふぇ" },
  { id: "0862", name: "タチフサグマ", en: "Obstagoon", type1: "あく", type2: "のま" },
  { id: "0863", name: "ニャイキング", en: "Perrserker", type1: "はが", type2: "" },
  { id: "0864", name: "サニゴーン", en: "Cursola", type1: "ごす", type2: "" },
  { id: "0865", name: "ネギガナイト", en: "Sirfetch'd", type1: "かく", type2: "" },
  { id: "0866", name: "バリコオル", en: "Mr. Rime", type1: "こお", type2: "えす" },
  { id: "0867", name: "デスバーン", en: "Runerigus", type1: "じめ", type2: "ごす" },
  { id: "0868", name: "マホミル", en: "Milcery", type1: "ふぇ", type2: "" },
  { id: "0869", name: "マホイップ", en: "Alcremie", type1: "ふぇ", type2: "" },
  { id: "0870", name: "タイレーツ", en: "Falinks", type1: "かく", type2: "" },
  { id: "0871", name: "バチンウニ", en: "Pincurchin", type1: "でん", type2: "" },
  { id: "0872", name: "ユキハミ", en: "Snom", type1: "こお", type2: "むし" },
  { id: "0873", name: "モスノウ", en: "Frosmoth", type1: "こお", type2: "むし" },
  { id: "0874", name: "イシヘンジン", en: "Stonjourner", type1: "いわ", type2: "" },
  { id: "0875", name: "コオリッポ", en: "Eiscue", type1: "こお", type2: "" },
  { id: "0876", sugata: "00", name: "イエッサン(♂)", en: "Indeedee", type1: "えす", type2: "のま" },
  { id: "0876", sugata: "01", name: "イエッサン(♀)", en: "Indeedee", type1: "えす", type2: "のま" },
  { id: "0877", name: "モルペコ", en: "Morpeko", type1: "でん", type2: "あく" },
  { id: "0878", name: "ゾウドウ", en: "Cufant", type1: "はが", type2: "" },
  { id: "0879", name: "ダイオウドウ", en: "Copperajah", type1: "はが", type2: "" },
  { id: "0880", name: "パッチラゴン", en: "Dracozolt", type1: "でん", type2: "どら" },
  { id: "0881", name: "パッチルドン", en: "Arctozolt", type1: "でん", type2: "こお" },
  { id: "0882", name: "ウオノラゴン", en: "Dracovish", type1: "みず", type2: "どら" },
  { id: "0883", name: "ウオチルドン", en: "Arctovish", type1: "みず", type2: "こお" },
  { id: "0884", name: "ジュラルドン", en: "Duraludon", type1: "はが", type2: "どら" },
  { id: "0885", name: "ドラメシヤ", en: "Dreepy", type1: "どら", type2: "ごす" },
  { id: "0886", name: "ドロンチ", en: "Drakloak", type1: "どら", type2: "ごす" },
  { id: "0887", name: "ドラパルト", en: "Dragapult", type1: "どら", type2: "ごす" },
  { id: "0888", name: "ザシアン", en: "Zacian", type1: "ふぇ", type2: "" },
  { id: "0889", name: "ザマゼンタ", en: "Zamazenta", type1: "かく", type2: "はが" },
  { id: "0890", name: "ムゲンダイナ", en: "Eternatus", type1: "どく", type2: "どら" },
  { id: "0891", name: "ダクマ", en: "Kubfu", type1: "かく", type2: "" },
  { id: "0892", sugata: "00", name: "ウーラオス(いちげき)", en: "Urshifu", type1: "かく", type2: "あく" },
  { id: "0892", sugata: "01", name: "ウーラオス(れんげき)", en: "Urshifu", type1: "かく", type2: "みず" },
  { id: "0893", name: "ザルード", en: "Zarude", type1: "あく", type2: "くさ" },
  { id: "0894", name: "レジエレキ", en: "Regieleki", type1: "でん", type2: "" },
  { id: "0895", name: "レジドラゴ", en: "Regidrago", type1: "どら", type2: "" },
  { id: "0896", name: "ブリザポス", en: "Glastrier", type1: "こお", type2: "" },
  { id: "0897", name: "レイスポス", en: "Spectrier", type1: "ごす", type2: "" },
  { id: "0898", sugata: "00", name: "バドレックス", en: "Calyrex", type1: "えす", type2: "くさ" },
  { id: "0898", sugata: "01", name: "バドレックス(はくば)", en: "Calyrex", type1: "えす", type2: "こお" },
  { id: "0898", sugata: "02", name: "バドレックス(こくば)", en: "Calyrex", type1: "えす", type2: "ごす" },
  { id: "0899", name: "アヤシシ", en: "Wyrdeer", type1: "のま", type2: "えす" },
  { id: "0900", name: "バサギリ", en: "Kleavor", type1: "むし", type2: "いわ" },
  { id: "0901", name: "ガチグマ", en: "Ursaluna", type1: "じめ", type2: "のま" },
  { id: "0902", sugata: "00", name: "イダイトウ(♂)", en: "Basculegion", type1: "みず", type2: "ごす" },
  { id: "0902", sugata: "01", name: "イダイトウ(♀)", en: "Basculegion", type1: "みず", type2: "ごす" },
  { id: "0903", name: "オオニューラ", en: "Sneasler", type1: "かく", type2: "どく" },
  { id: "0904", name: "ハリーマン", en: "Overqwil", type1: "あく", type2: "どく" },
  { id: "0905", sugata: "00", name: "ラブトロス(けしん)", en: "Enamorus", type1: "ふぇ", type2: "ひこ" },
  { id: "0905", sugata: "01", name: "ラブトロス(れいじゅう)", en: "Enamorus", type1: "ふぇ", type2: "ひこ" },
  { id: "0906", name: "ニャオハ", en: "Sprigatito", type1: "くさ", type2: "" },
  { id: "0907", name: "ニャローテ", en: "Floragato", type1: "くさ", type2: "" },
  { id: "0908", name: "マスカーニャ", en: "Meowscarada", type1: "くさ", type2: "あく" },
  { id: "0909", name: "ホゲータ", en: "Fuecoco", type1: "ほの", type2: "" },
  { id: "0910", name: "アチゲータ", en: "Crocalor", type1: "ほの", type2: "" },
  { id: "0911", name: "ラウドボーン", en: "Skeledirge", type1: "ほの", type2: "ごす" },
  { id: "0912", name: "クワッス", en: "Quaxly", type1: "みず", type2: "" },
  { id: "0913", name: "ウェルカモ", en: "Quaxwell", type1: "みず", type2: "" },
  { id: "0914", name: "ウェーニバル", en: "Quaquaval", type1: "みず", type2: "かく" },
  { id: "0915", name: "グルトン", en: "Lechonk", type1: "のま", type2: "" },
  { id: "0916", sugata: "00", name: "パフュートン(♂)", en: "Oinkologne", type1: "のま", type2: "" },
  { id: "0916", sugata: "01", name: "パフュートン(♀)", en: "Oinkologne", type1: "のま", type2: "" },
  { id: "0917", name: "タマンチュラ", en: "Tarountula", type1: "むし", type2: "" },
  { id: "0918", name: "ワナイダー", en: "Spidops", type1: "むし", type2: "" },
  { id: "0919", name: "マメバッタ", en: "Nymble", type1: "むし", type2: "" },
  { id: "0920", name: "エクスレッグ", en: "Lokix", type1: "むし", type2: "あく" },
  { id: "0921", name: "パモ", en: "Pawmi", type1: "でん", type2: "" },
  { id: "0922", name: "パモット", en: "Pawmo", type1: "でん", type2: "かく" },
  { id: "0923", name: "パーモット", en: "Pawmot", type1: "でん", type2: "かく" },
  { id: "0924", name: "ワッカネズミ", en: "Tandemaus", type1: "のま", type2: "" },
  { id: "0925", name: "イッカネズミ", en: "Maushold", type1: "のま", type2: "" },
  { id: "0926", name: "パピモッチ", en: "Fidough", type1: "ふぇ", type2: "" },
  { id: "0927", name: "バウッツェル", en: "Dachsbun", type1: "ふぇ", type2: "" },
  { id: "0928", name: "ミニーブ", en: "Smoliv", type1: "くさ", type2: "のま" },
  { id: "0929", name: "オリーニョ", en: "Dolliv", type1: "くさ", type2: "のま" },
  { id: "0930", name: "オリーヴァ", en: "Arboliva", type1: "くさ", type2: "のま" },
  { id: "0931", sugata: "00", name: "イキリンコ(グリーン)", en: "Squawkabilly", type1: "のま", type2: "ひこ" },
  { id: "0931", sugata: "01", name: "イキリンコ(ブルーフ)", en: "Squawkabilly", type1: "のま", type2: "ひこ" },
  { id: "0931", sugata: "02", name: "イキリンコ(イエロー)", en: "Squawkabilly", type1: "のま", type2: "ひこ" },
  { id: "0931", sugata: "03", name: "イキリンコ(ホワイト)", en: "Squawkabilly", type1: "のま", type2: "ひこ" },
  { id: "0932", name: "コジオ", en: "Nacli", type1: "いわ", type2: "" },
  { id: "0933", name: "ジオヅム", en: "Naclstack", type1: "いわ", type2: "" },
  { id: "0934", name: "キョジオーン", en: "Garganacl", type1: "いわ", type2: "" },
  { id: "0935", name: "カルボウ", en: "Charcadet", type1: "ほの", type2: "" },
  { id: "0936", name: "グレンアルマ", en: "Armarouge", type1: "ほの", type2: "えす" },
  { id: "0937", name: "ソウブレイズ", en: "Ceruledge", type1: "ほの", type2: "ごす" },
  { id: "0938", name: "ズピカ", en: "Tadbulb", type1: "でん", type2: "" },
  { id: "0939", name: "ハラバリー", en: "Bellibolt", type1: "でん", type2: "" },
  { id: "0940", name: "カイデン", en: "Wattrel", type1: "でん", type2: "ひこ" },
  { id: "0941", name: "タイカイデン", en: "Kilowattrel", type1: "でん", type2: "ひこ" },
  { id: "0942", name: "オラチフ", en: "Maschiff", type1: "あく", type2: "" },
  { id: "0943", name: "マフィティフ", en: "Mabosstiff", type1: "あく", type2: "" },
  { id: "0944", name: "シルシュルー", en: "Shroodle", type1: "どく", type2: "のま" },
  { id: "0945", name: "タギングル", en: "Grafaiai", type1: "どく", type2: "のま" },
  { id: "0946", name: "アノクサ", en: "Bramblin", type1: "くさ", type2: "ごす" },
  { id: "0947", name: "アノホラグサ", en: "Brambleghast", type1: "くさ", type2: "ごす" },
  { id: "0948", name: "ノノクラゲ", en: "Toedscool", type1: "じめ", type2: "くさ" },
  { id: "0949", name: "リククラゲ", en: "Toedscruel", type1: "じめ", type2: "くさ" },
  { id: "0950", name: "ガケガニ", en: "Klawf", type1: "いわ", type2: "" },
  { id: "0951", name: "カプサイジ", en: "Capsakid", type1: "くさ", type2: "" },
  { id: "0952", name: "スコヴィラン", en: "Scovillain", type1: "くさ", type2: "ほの" },
  { id: "0953", name: "シガロコ", en: "Rellor", type1: "むし", type2: "" },
  { id: "0954", name: "ベラカス", en: "Rabsca", type1: "むし", type2: "えす" },
  { id: "0955", name: "ヒラヒナ", en: "Flittle", type1: "えす", type2: "" },
  { id: "0956", name: "クエスパトラ", en: "Espathra", type1: "えす", type2: "" },
  { id: "0957", name: "カヌチャン", en: "Tinkatink", type1: "ふぇ", type2: "はが" },
  { id: "0958", name: "ナカヌチャン", en: "Tinkatuff", type1: "ふぇ", type2: "はが" },
  { id: "0959", name: "デカヌチャン", en: "Tinkaton", type1: "ふぇ", type2: "はが" },
  { id: "0960", name: "ウミディグダ", en: "Wiglett", type1: "みず", type2: "" },
  { id: "0961", name: "ウミトリオ", en: "Wugtrio", type1: "みず", type2: "" },
  { id: "0962", name: "オトシドリ", en: "Bombirdier", type1: "ひこ", type2: "あく" },
  { id: "0963", name: "ナミイルカ", en: "Finizen", type1: "みず", type2: "" },
  { id: "0964", name: "イルカマン", en: "Palafin", type1: "みず", type2: "" },
  { id: "0965", name: "ブロロン", en: "Varoom", type1: "はが", type2: "どく" },
  { id: "0966", name: "ブロロローム", en: "Revavroom", type1: "はが", type2: "どく" },
  { id: "0967", name: "モトトカゲ", en: "Cyclizar", type1: "どら", type2: "のま" },
  { id: "0968", name: "ミミズズ", en: "Orthworm", type1: "はが", type2: "" },
  { id: "0969", name: "キラーメ", en: "Glimmet", type1: "いわ", type2: "どく" },
  { id: "0970", name: "キラフロル", en: "Glimmora", type1: "いわ", type2: "どく" },
  { id: "0971", name: "ボチ", en: "Greavard", type1: "ごす", type2: "" },
  { id: "0972", name: "ハカドッグ", en: "Houndstone", type1: "ごす", type2: "" },
  { id: "0973", name: "カラミンゴ", en: "Flamigo", type1: "ひこ", type2: "かく" },
  { id: "0974", name: "アルクジラ", en: "Cetoddle", type1: "こお", type2: "" },
  { id: "0975", name: "ハルクジラ", en: "Cetitan", type1: "こお", type2: "" },
  { id: "0976", name: "ミガルーサ", en: "Veluza", type1: "みず", type2: "えす" },
  { id: "0977", name: "ヘイラッシャ", en: "Dondozo", type1: "みず", type2: "" },
  { id: "0978", sugata: "00", name: "シャリタツ(そった)", en: "Tatsugiri", type1: "どら", type2: "みず" },
  { id: "0978", sugata: "01", name: "シャリタツ(たれた)", en: "Tatsugiri", type1: "どら", type2: "みず" },
  { id: "0978", sugata: "02", name: "シャリタツ(のびた)", en: "Tatsugiri", type1: "どら", type2: "みず" },
  { id: "0979", name: "コノヨザル", en: "Annihilape", type1: "かく", type2: "ごす" },
  { id: "0980", name: "ドオー", en: "Clodsire", type1: "どく", type2: "じめ" },
  { id: "0981", name: "リキキリン", en: "Farigiraf", type1: "のま", type2: "えす" },
  { id: "0982", name: "ノココッチ", en: "Dudunsparce", type1: "のま", type2: "" },
  { id: "0983", name: "ドドゲザン", en: "Kingambit", type1: "あく", type2: "はが" },
  { id: "0984", name: "イダイナキバ", en: "Great Tusk", type1: "じめ", type2: "かく" },
  { id: "0985", name: "サケブシッポ", en: "Scream Tail", type1: "ふぇ", type2: "えす" },
  { id: "0986", name: "アラブルタケ", en: "Brute Bonnet", type1: "くさ", type2: "あく" },
  { id: "0987", name: "ハバタクカミ", en: "Flutter Mane", type1: "ごす", type2: "ふぇ" },
  { id: "0988", name: "チヲハウハネ", en: "Slither Wing", type1: "むし", type2: "かく" },
  { id: "0989", name: "スナノケガワ", en: "Sandy Shocks", type1: "でん", type2: "じめ" },
  { id: "0990", name: "テツノワダチ", en: "Iron Treads", type1: "じめ", type2: "はが" },
  { id: "0991", name: "テツノツツミ", en: "Iron Bundle", type1: "こお", type2: "みず" },
  { id: "0992", name: "テツノカイナ", en: "Iron Hands", type1: "かく", type2: "でん" },
  { id: "0993", name: "テツノコウベ", en: "Iron Jugulis", type1: "あく", type2: "ひこ" },
  { id: "0994", name: "テツノドクガ", en: "Iron Moth", type1: "ほの", type2: "どく" },
  { id: "0995", name: "テツノイバラ", en: "Iron Thorns", type1: "いわ", type2: "でん" },
  { id: "0996", name: "セビエ", en: "Frigibax", type1: "どら", type2: "こお" },
  { id: "0997", name: "セゴール", en: "Arctibax", type1: "どら", type2: "こお" },
  { id: "0998", name: "セグレイブ", en: "Baxcalibur", type1: "どら", type2: "こお" },
  { id: "0999", sugata: "00", name: "コレクレー(はこ)", en: "Gimmighoul", type1: "ごす", type2: "" },
  { id: "0999", sugata: "01", name: "コレクレー(とほ)", en: "Gimmighoul", type1: "ごす", type2: "" },
  { id: "1000", name: "サーフゴー", en: "Gholdengo", type1: "はが", type2: "ごす" },
  { id: "1001", name: "チオンジェン", en: "Wo-Chien", type1: "あく", type2: "くさ" },
  { id: "1002", name: "パオジアン", en: "Chien-Pao", type1: "あく", type2: "こお" },
  { id: "1003", name: "ディンルー", en: "Ting-Lu", type1: "あく", type2: "じめ" },
  { id: "1004", name: "イーユイ", en: "Chi-Yu", type1: "あく", type2: "ほの" },
  { id: "1005", name: "トドロクツキ", en: "Roaring Moon", type1: "どら", type2: "あく" },
  { id: "1006", name: "テツノブジン", en: "Iron Valiant", type1: "ふぇ", type2: "かく" },
  { id: "1007", name: "コライドン", en: "Koraidon", type1: "かく", type2: "どら" },
  { id: "1008", name: "ミライドン", en: "Miraidon", type1: "でん", type2: "どら" },
  { id: "1009", name: "ウネルミナモ", en: "Walking Wake", type1: "みず", type2: "どら" },
  { id: "1010", name: "テツノイサハ", en: "Iron Leaves", type1: "くさ", type2: "えす" },
];
