export const metadata = {
  title: "あいてむ君SV(β)",
  description: "Generated by Next.js",
  // icons: { icon: { url: "/favicon.ico", type: "image/ico" } },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
